---
title: "Simulation Model Results"
author: "Ze Yu Zhong"
date: "21/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
################
##Load Libraries
################

library(tidyverse)
library(keras)
library(quantreg)
library(ggplot2)
library(forecast)
library(rlist)
library(Metrics)
library(ranger)
library(caret)
library(forcats)
library(xtable)
library(randomForestSRC)
library(kableExtra)

#Parallel Computing
library(foreach)
library(doFuture)
#Registering
registerDoFuture()
plan(multisession)

set.seed(27935248)
```

```{r load_final_results}
## Chunk to load final results list (just load this to avoid bothering with combining different results list)

# g1_A1_nosv_0_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_results_all.RDS")
# g2_A1_nosv_0_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_results_all.RDS")
# g3_A1_nosv_0_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_results_all.RDS")

g1_A1_sv_0.01_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_results_all.RDS")
g2_A1_sv_0.01_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_results_all.RDS")
g3_A1_sv_0.01_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_results_all.RDS")

g1_A1_sv_0.1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_results_all.RDS")
g2_A1_sv_0.1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_results_all.RDS")
g3_A1_sv_0.1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_results_all.RDS")

g1_A1_sv_1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_results_all.RDS")
g2_A1_sv_1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_results_all.RDS")
g3_A1_sv_1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_results_all.RDS")
```

```{r performance_functions}
## For a given simulation results list, collect all the loss dataframes into a big, tidy DF for a SINGLE realization

gen_tidy_loss_df <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  df <- foreach(sample = (1:3), .combine = "rbind") %do% {
    rbind(
      cbind(model = "LM_MSE", sample = sample, simulation_results_list[[realization_no]]$LM_MSE[[sample]]$loss_stats),
      cbind(model = "LM_MAE", sample = sample, simulation_results_list[[realization_no]]$LM_MAE[[sample]]$loss_stats),
      ################################################################################################
      cbind(model = "ELN_MSE", sample = sample, simulation_results_list[[realization_no]]$ELN_MSE[[sample]]$loss_stats),
      cbind(model = "ELN_MAE", sample = sample, simulation_results_list[[realization_no]]$ELN_MAE[[sample]]$loss_stats),
      ################################################################################################
      cbind(model = "RF_MSE", sample = sample, simulation_results_list[[realization_no]]$RF_MSE[[sample]]$loss_stats),
      cbind(model = "RF_MAE", sample = sample, simulation_results_list[[realization_no]]$RF_MAE[[sample]]$loss_stats),
      ################################################################################################
      cbind(model = "NN1_MSE", sample = sample, simulation_results_list[[realization_no]]$NN1_MSE[[sample]]$loss_stats),
      cbind(model = "NN1_MAE", sample = sample, simulation_results_list[[realization_no]]$NN1_MAE[[sample]]$loss_stats),

      cbind(model = "NN2_MSE", sample = sample, simulation_results_list[[realization_no]]$NN2_MSE[[sample]]$loss_stats),
      cbind(model = "NN2_MAE", sample = sample, simulation_results_list[[realization_no]]$NN2_MAE[[sample]]$loss_stats),

      cbind(model = "NN3_MSE", sample = sample, simulation_results_list[[realization_no]]$NN3_MSE[[sample]]$loss_stats),
      cbind(model = "NN3_MAE", sample = sample, simulation_results_list[[realization_no]]$NN3_MAE[[sample]]$loss_stats),

      cbind(model = "NN4_MSE", sample = sample, simulation_results_list[[realization_no]]$NN4_MSE[[sample]]$loss_stats),
      cbind(model = "NN4_MAE", sample = sample, simulation_results_list[[realization_no]]$NN4_MAE[[sample]]$loss_stats),

      cbind(model = "NN5_MSE", sample = sample, simulation_results_list[[realization_no]]$NN5_MSE[[sample]]$loss_stats),
      cbind(model = "NN5_MAE", sample = sample, simulation_results_list[[realization_no]]$NN5_MAE[[sample]]$loss_stats),
      #################################################################################################
      cbind(model = "LSTM_MSE", sample = sample, simulation_results_list[[realization_no]]$LSTM_MSE[[sample]]$loss_stats),
      cbind(model = "LSTM_MAE", sample = sample, simulation_results_list[[realization_no]]$LSTM_MAE[[sample]]$loss_stats),
      #################################################################################################
      cbind(model = "FFORMA_MSE", sample = sample, simulation_results_list[[realization_no]]$FFORMA_MSE[[sample]]$loss_stats),
      cbind(model = "FFORMA_MAE", sample = sample, simulation_results_list[[realization_no]]$FFORMA_MAE[[sample]]$loss_stats),
      #################################################################################################
      cbind(model = "DeepAR", sample = sample, simulation_results_list[[realization_no]]$DeepAR[[sample]]$loss_stats)
    )
  }
  cbind(realization_no = realization_no, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, df)
}

# Function to iterate over all realizations

all_realize_loss_df <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = (1:5), .combine = "rbind") %do% {
    gen_tidy_loss_df(simulation_results_list, realization_no, dgp_spec, SV, cross_corr)
  }
}

all_loss_df <- rbind(
  # all_realize_loss_df(g1_A1_nosv_0_results_all, dgp_spec = "g1", SV = 0, cross_corr = 0),
  # all_realize_loss_df(g2_A1_nosv_0_results_all, dgp_spec = "g2", SV = 0, cross_corr = 0),
  # all_realize_loss_df(g3_A1_nosv_0_results_all, dgp_spec = "g3", SV = 0, cross_corr = 0),
  
  all_realize_loss_df(g1_A1_sv_0.01_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.01),
  all_realize_loss_df(g2_A1_sv_0.01_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.01),
  all_realize_loss_df(g3_A1_sv_0.01_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.01),
  
  all_realize_loss_df(g1_A1_sv_0.1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.1),
  all_realize_loss_df(g2_A1_sv_0.1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.1),
  all_realize_loss_df(g3_A1_sv_0.1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.1),
  
  all_realize_loss_df(g1_A1_sv_1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 1),
  all_realize_loss_df(g2_A1_sv_1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 1),
  all_realize_loss_df(g3_A1_sv_1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 1)
)

all_loss_df_averaged <- all_loss_df %>%
  data.frame() %>%
  group_by(model, dgp_spec, sample, SV, cross_corr) %>%
  summarise(validation_MAE = mean(validation_MAE), validation_MSE = mean(validation_MSE), 
            validation_RMSE = mean(validation_RMSE), validation_RSquare = mean(validation_RSquare),
              
            test_MAE = mean(test_MAE), test_MSE = mean(test_MSE), 
            test_RMSE = mean(test_RMSE), test_RSquare = mean(test_RSquare)
            )

## Save to csv

write.csv(all_loss_df_averaged, file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_loss_averaged.csv")
write.csv(all_loss_df, file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_loss.csv")

########
## Take the above and average over all training/test samples to make cleaner graphs/tables

all_loss_df_averaged_sam <- all_loss_df_averaged %>%
  group_by(model, dgp_spec, SV, cross_corr) %>%
  summarise(validation_MAE = mean(validation_MAE), validation_MSE = mean(validation_MSE), 
            validation_RMSE = mean(validation_RMSE), validation_RSquare = mean(validation_RSquare),
              
            test_MAE = mean(test_MAE), test_MSE = mean(test_MSE), 
            test_RMSE = mean(test_RMSE), test_RSquare = mean(test_RSquare)
            ) %>%
  ## Create a new column for each loss metric averaged over all specifications for ordering purposes later
  group_by(model, cross_corr) %>%
  mutate(validation_MAE_ave = mean(validation_MAE), validation_MSE_ave = mean(validation_MSE), 
            validation_RMSE_ave = mean(validation_RMSE), validation_RSquare_ave = mean(validation_RSquare),
              
            test_MAE_ave = mean(test_MAE), test_MSE_ave = mean(test_MSE), 
            test_RMSE_ave = mean(test_RMSE), test_RSquare_ave = mean(test_RSquare)
            )

write.csv(all_loss_df_averaged_sam, file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_loss_averaged_sam.csv")

#############################################################################
# Function to collate variable importance

normalize_variable_importance <- function(variable_importance_df) {
  variable_importance_df %>%
    # Add a very very tiny value so that division by zero does not occur
    mutate(importance = importance + 1e-100) %>%
    mutate(importance = importance + abs(min(importance))) %>%
    mutate(importance = importance/sum(importance))
}

gen_tidy_vi <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  df <- foreach(sample = 1:3, .combine = "rbind") %do% {
    rbind(
      cbind(model = "LM_MSE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$LM_MSE[[sample]]$variable_importance)),
      cbind(model = "LM_MAE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$LM_MAE[[sample]]$variable_importance)),
      
      ################################################################################################
      
      cbind(model = "ELN_MSE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$ELN_MSE[[sample]]$variable_importance)),
      cbind(model = "ELN_MAE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$ELN_MAE[[sample]]$variable_importance)),
      
      ################################################################################################
      
      cbind(model = "RF_MSE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$RF_MSE[[sample]]$variable_importance)),
      cbind(model = "RF_MAE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$RF_MAE[[sample]]$variable_importance)),
      
      ################################################################################################
      
      cbind(model = "NN1_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN1_MSE[[sample]]$variable_importance)),
      cbind(model = "NN1_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN1_MAE[[sample]]$variable_importance)),

      cbind(model = "NN2_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN2_MSE[[sample]]$variable_importance)),
      cbind(model = "NN2_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN2_MAE[[sample]]$variable_importance)),

      cbind(model = "NN3_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN3_MSE[[sample]]$variable_importance)),
      cbind(model = "NN3_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN3_MAE[[sample]]$variable_importance)),

      cbind(model = "NN4_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN4_MSE[[sample]]$variable_importance)),
      cbind(model = "NN4_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN4_MAE[[sample]]$variable_importance)),

      cbind(model = "NN5_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN5_MSE[[sample]]$variable_importance)),
      cbind(model = "NN5_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN5_MAE[[sample]]$variable_importance)),
      
      ################################################################################################
      
      cbind(model = "LSTM_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$LSTM_MSE[[sample]]$variable_importance)),
      
      cbind(model = "LSTM_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$LSTM_MAE[[sample]]$variable_importance))
    )
  }
  cbind(realization_no = realization_no, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, df)
}

# Iterate over all realizations

all_realize_vi <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = (1:5), .combine = "rbind") %do% {
    gen_tidy_vi(simulation_results_list, realization_no, dgp_spec, SV, cross_corr)
  }
}

all_vi_df <- rbind(
  # all_realize_vi(g1_A1_nosv_0_results_all, dgp_spec = "g1", SV = 0, cross_corr = 0),
  # all_realize_vi(g2_A1_nosv_0_results_all, dgp_spec = "g2", SV = 0, cross_corr = 0),
  # all_realize_vi(g3_A1_nosv_0_results_all, dgp_spec = "g3", SV = 0, cross_corr = 0),
  
  all_realize_vi(g1_A1_sv_0.01_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.01),
  all_realize_vi(g2_A1_sv_0.01_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.01),
  all_realize_vi(g3_A1_sv_0.01_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.01),
  
  all_realize_vi(g1_A1_sv_0.1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.1),
  all_realize_vi(g2_A1_sv_0.1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.1),
  all_realize_vi(g3_A1_sv_0.1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.1),
  
  all_realize_vi(g1_A1_sv_1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 1),
  all_realize_vi(g2_A1_sv_1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 1),
  all_realize_vi(g3_A1_sv_1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 1)
)

all_vi_df_averaged <- all_vi_df %>%
  group_by(model, dgp_spec, sample, SV, cross_corr, variable) %>%
  summarise(importance = mean(importance))
```

```{r plots}
#######################################################################
# Test Statistics

breaks <- levels(all_loss_df_averaged$model)
labels <- as.expression(breaks)
labels[[2]] <- bquote(bold(.(labels[[2]])))
labels[[4]] <- bquote(bold(.(labels[[4]])))
labels[[6]] <- bquote(bold(.(labels[[6]])))
labels[[16]] <- bquote(bold(.(labels[[16]])))

## Plots showing that quantile loss is better
all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  filter(model == "LM_MAE" | model == "LM_MSE" 
         | model == "ELN_MAE" | model == "ELN_MSE"
         | model == "RF_MAE" | model == "RF_MSE"
         | model == "NN5_MAE" | model == "NN5_MSE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MAE, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mae_pre_all.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  filter(model == "LM_MAE" | model == "LM_MSE" 
         | model == "ELN_MAE" | model == "ELN_MSE"
         | model == "RF_MAE" | model == "RF_MSE"
         | model == "NN5_MAE" | model == "NN5_MSE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MSE, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mse_pre_all.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  filter(model == "LM_MAE" | model == "LM_MSE" 
         | model == "ELN_MAE" | model == "ELN_MSE"
         | model == "RF_MAE" | model == "RF_MSE"
         | model == "NN5_MAE" | model == "NN5_MSE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RSquare, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rsquare_pre_all.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

###########################
## Plots for presentation

breaks <- levels(all_loss_df_averaged$model)
labels <- as.expression(breaks)
labels[[4]] <- bquote(bold(.(labels[[4]])))
labels[[6]] <- bquote(bold(.(labels[[6]])))

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  filter(model == "LM_MSE" 
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MAE, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mae_pre.pdf")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  filter(model == "LM_MSE" 
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MSE, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mse_pre.pdf")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  filter(model == "LM_MSE" 
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RSquare, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rsquare_pre.pdf")

###################################################################################################################

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RMSE, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rmse.pdf")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  filter(model == "LM_MSE" 
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RSquare, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rsquare.pdf")

###############################################################################################################
###############################################################################################################
## More proper graphs that are much more readable
## Achieve this by only showing the best neural network

breaks <- levels(all_loss_df_averaged$model)
labels <- as.expression(breaks)
labels[[4]] <- bquote(bold(.(labels[[4]])))
labels[[6]] <- bquote(bold(.(labels[[6]])))

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  filter(model == "LM_MSE"
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MSE, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mse_small.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  filter(model == "LM_MSE"
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MAE, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mae_small.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  filter(model == "LM_MSE"
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RSquare, fill = sample), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rsquare_small.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

##############################################
## Focusing on only Neural Networks

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  filter(model == "NN1_MAE"
         | model == "NN2_MAE"
         | model == "NN3_MAE"
         | model == "NN4_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MSE, fill = sample), stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mse_small_nn.pdf")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  filter(model == "NN1_MAE"
         | model == "NN2_MAE"
         | model == "NN3_MAE"
         | model == "NN4_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MAE, fill = sample), stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mae_small_nn.pdf")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  filter(model == "NN1_MAE"
         | model == "NN2_MAE"
         | model == "NN3_MAE"
         | model == "NN4_MAE"
         | model == "NN5_MAE") %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RSquare, fill = sample), stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rsquare_small_nn.pdf")

## All Models

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  ggplot() +
  geom_bar(aes(x = model, y = test_MSE, fill = sample), stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mse.pdf")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  ggplot() +
  geom_bar(aes(x = model, y = test_MAE, fill = sample), stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mae.pdf")

all_loss_df_averaged %>%
  ungroup() %>%
  mutate(sample = as.factor(sample)) %>%
  ## Filter out certain models
  ggplot() +
  geom_bar(aes(x = model, y = test_RSquare, fill = sample), stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rsquare.pdf")
```

```{r tables}
#################################
## COMPREHENSIVE TABLES (SHOVE IN APPENDIX)
#################################
## Test MAE Comprehensive
model_sam <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(model)

cross_corr_sam <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(cross_corr)

g1_sam_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MAE) %>%
  rename(`Test MAE` = test_MAE) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g2_sam_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MAE) %>%
  rename(`Test MAE` = test_MAE) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g3_sam_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MAE) %>%
  rename(`Test MAE` = test_MAE) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(-dgp_spec, -cross_corr)

#######

g1_sam_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MSE) %>%
  rename(`Test MSE` = test_MSE) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g2_sam_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MSE) %>%
  rename(`Test MSE` = test_MSE) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g3_sam_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MSE) %>%
  rename(`Test MSE` = test_MSE) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(-dgp_spec, -cross_corr)

#########################

g1_sam_r2 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_RSquare) %>%
  rename(`Test $R^2$` = test_RSquare) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g2_sam_r2 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_RSquare) %>%
  rename(`Test $R^2$` = test_RSquare) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g3_sam_r2 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_RSquare) %>%
  rename(`Test $R^2$` = test_RSquare) %>%
  filter(cross_corr != 0) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(-dgp_spec, -cross_corr)

model_sam <- model_sam %>%
  mutate(model = str_replace(model, "_", "."))

cross_corr_sam <- cross_corr_sam %>%
  rename(Corr = cross_corr)

test_loss_latex <- cbind(model_sam, cross_corr_sam, 
                         g1_sam_mae, g1_sam_mse, g1_sam_r2, 
                         g2_sam_mae, g2_sam_mse, g2_sam_r2, 
                         g3_sam_mae, g3_sam_mse, g3_sam_r2) %>%
  kable(align = "c", format = "latex", booktabs = T, 
        escape = F, digits = 6, longtable = T) %>%
  add_header_above(c(" " = 1, " " = 1, "g1" = 3, "g2" = 3, "g3" = 3)) %>%
  kable_styling(font_size = 6,
                latex_options = c("repeat_header"),
                repeat_header_text = "") %>%
  collapse_rows(columns = c(1:2), valign = "middle")

test_loss_latex %>%
  cat(file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation/test_loss_latex.tex")
  
```

```{r small_tables}
## DIfferent methods are better on different specifications:
## Solution: make an "average" loss column across all specifications and order them by this metric

ordering_0.01_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  arrange(-desc(test_MAE_ave)) %>%
  dplyr::select(model) %>%
  unique()

ordering_1_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  arrange(-desc(test_MAE_ave)) %>%
  dplyr::select(model) %>%
  unique()

## Doesn't seem to be an easy way to choose which "sub method" is the best, just doing it manually from viewing above
ordering_0.01_mae <- c("ELN_MAE", "RF_MAE", "NN2_MAE", "NN1_MAE", "NN3_MAE")

ordering_1_mae <- c("ELN_MSE", "RF_MAE", "NN5_MAE", "NN4_MSE", "NN3_MAE")

g1_0.01 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MAE) %>%
  rename(g1 = test_MAE) %>%
  ## Filtering out so that we only have the quantile methods
  filter(model %in% ordering_0.01_mae) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g2_0.01 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MAE) %>%
  rename(g2 = test_MAE) %>%
  ## Filtering out so that we only have the quantile methods %>%
  filter(model %in% ordering_0.01_mae) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g3_0.01 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MAE) %>%
  rename(g3 = test_MAE) %>%
  filter(model %in% ordering_0.01_mae) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

################

g1_1 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MAE) %>%
  rename(g1 = test_MAE) %>%
  ## Filtering out so that we only have the quantile methods
  filter(model %in% ordering_1_mae) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g2_1 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MAE) %>%
  rename(g2 = test_MAE) %>%
  ## Filtering out so that we only have the quantile methods %>%
  filter(model %in% ordering_1_mae) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g3_1 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MAE) %>%
  rename(g3 = test_MAE) %>%
  filter(model %in% ordering_1_mae) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

sam_0.01 <- cbind(cross_corr = 0.01, model = ordering_0.01_mae, g1_0.01, g2_0.01, g3_0.01) %>%
  ## Round off to significant digits here because cell_spec doesn't play nicely with digits argument
  ## Also bolden the "best" statistics
  mutate(g1 = cell_spec(round(g1, 6), format = "latex", 
                        bold = if_else(g1 == min(g1), 1, 0)),
         g2 = cell_spec(round(g2, 6), format = "latex", 
                        bold = if_else(g2 == min(g2), 1, 0)),
         g3 = cell_spec(round(g3, 6), format = "latex", 
                        bold = if_else(g3 == min(g3), 1, 0)))
sam_1 <- cbind(cross_corr = 1, model = ordering_1_mae, g1_1, g2_1, g3_1) %>%
  mutate(g1 = cell_spec(round(g1, 6), format = "latex", 
                        bold = if_else(g1 == min(g1), 1, 0)),
         g2 = cell_spec(round(g2, 6), format = "latex", 
                        bold = if_else(g2 == min(g2), 1, 0)),
         g3 = cell_spec(round(g3, 6), format = "latex", 
                        bold = if_else(g3 == min(g3), 1, 0)))

## This is all working beautifully, now to figure how to bold specific cells...

test_mae_latex <- rbind(sam_0.01, sam_1) %>% 
  data.frame() %>%
  rename(Corr = cross_corr) %>%
  mutate(model = str_replace(model, "_", ".")) %>%
  mutate(Corr = cell_spec(Corr, angle = 90, format = "latex")) %>%
  kable(align = "c", format = "latex", booktabs = T, escape = F) %>%
  kable_styling(full_width = F, font_size = 8) %>%
  add_header_above(c(" " = 1, " " = 1, "Test MAE" = 3)) %>%
  collapse_rows(columns = c(1), valign = "middle", latex_hline = "major")

test_mae_latex %>%
  cat(file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation/test_mae_latex.tex")
```

```{r}
## Repeat all of the Abvoe for now for Test_MSE
## DIfferent methods are better on different specifications:
## Solution: make an "average" loss column across all specifications and order them by this metric

ordering_0.01_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  arrange(-desc(test_MSE_ave)) %>%
  dplyr::select(model) %>%
  unique()

ordering_1_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  arrange(-desc(test_MSE_ave)) %>%
  dplyr::select(model) %>%
  unique()

## Doesn't seem to be an easy way to choose which "sub method" is the best, just doing it manually from viewing above
ordering_0.01_mse <- c("ELN_MAE", "RF_MAE", "NN2_MAE", "NN1_MAE", "NN3_MAE")

ordering_1_mse <- c("ELN_MSE", "RF_MAE", "NN5_MAE", "NN3_MAE", "NN4_MSE")

g1_0.01 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MSE) %>%
  rename(g1 = test_MSE) %>%
  ## Filtering out so that we only have the quantile methods
  filter(model %in% ordering_0.01_mse) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g2_0.01 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MSE) %>%
  rename(g2 = test_MSE) %>%
  ## Filtering out so that we only have the quantile methods %>%
  filter(model %in% ordering_0.01_mse) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g3_0.01 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MSE) %>%
  rename(g3 = test_MSE) %>%
  filter(model %in% ordering_0.01_mse) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

################

g1_1 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MSE) %>%
  rename(g1 = test_MSE) %>%
  ## Filtering out so that we only have the quantile methods
  filter(model %in% ordering_1_mse) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g2_1 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MSE) %>%
  rename(g2 = test_MSE) %>%
  ## Filtering out so that we only have the quantile methods %>%
  filter(model %in% ordering_1_mse) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

g3_1 <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 1) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(model, dgp_spec, cross_corr, test_MSE) %>%
  rename(g3 = test_MSE) %>%
  filter(model %in% ordering_1_mse) %>%
  dplyr::select(-model, -dgp_spec, -cross_corr)

sam_0.01 <- cbind(cross_corr = 0.01, model = ordering_0.01_mse, g1_0.01, g2_0.01, g3_0.01) %>%
  ## Round off to significant digits here because cell_spec doesn't play nicely with digits argument
  ## Also bolden the "best" statistics
  mutate(g1 = cell_spec(round(g1, 6), format = "latex", 
                        bold = if_else(g1 == min(g1), 1, 0)),
         g2 = cell_spec(round(g2, 6), format = "latex", 
                        bold = if_else(g2 == min(g2), 1, 0)),
         g3 = cell_spec(round(g3, 6), format = "latex", 
                        bold = if_else(g3 == min(g3), 1, 0)))
sam_1 <- cbind(cross_corr = 1, model = ordering_1_mse, g1_1, g2_1, g3_1) %>%
  mutate(g1 = cell_spec(round(g1, 6), format = "latex", 
                        bold = if_else(g1 == min(g1), 1, 0)),
         g2 = cell_spec(round(g2, 6), format = "latex", 
                        bold = if_else(g2 == min(g2), 1, 0)),
         g3 = cell_spec(round(g3, 6), format = "latex", 
                        bold = if_else(g3 == min(g3), 1, 0)))

test_mse_latex <- rbind(sam_0.01, sam_1) %>% 
  data.frame() %>%
  rename(Corr = cross_corr) %>%
  mutate(model = str_replace(model, "_", ".")) %>%
  mutate(Corr = cell_spec(Corr, angle = 90, format = "latex")) %>%
  kable(align = "c", format = "latex", booktabs = T, escape = F) %>%
  kable_styling(full_width = F, font_size = 8) %>%
  add_header_above(c(" " = 1, " " = 1, "Test MSE" = 3)) %>%
  collapse_rows(columns = c(1), valign = "middle", latex_hline = "major")

test_mse_latex %>%
  cat(file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation/test_mse_latex.tex")
```

```{r variable_importance_plots}
# Variable Importance Plots

breaks <- levels(all_vi_df_averaged$variable)
labels <- as.expression(breaks)
labels[[1]] <- bquote(bold(.(labels[[1]])))
labels[[2]] <- bquote(bold(.(labels[[2]])))
labels[[3]] <- bquote(bold(.(labels[[3]])))
labels[[303]] <- bquote(bold(.(labels[[303]])))

## Plots for PRESENTATION
## Average over all samples
all_vi_df_averaged_sam <- all_vi_df_averaged %>%
  group_by(dgp_spec, model, variable, cross_corr) %>%
  summarise(importance = mean(importance)) %>%
  ungroup()

## Find the most important variables across all variables over all methods
important_variables_g1 <- all_vi_df_averaged_sam %>%
  filter(dgp_spec == "g1") %>%
  group_by(variable) %>%
  summarise(importance = mean(importance)) %>%
  arrange(desc(importance)) %>%
  ## Select the top 10
  head(10) %>%
  dplyr::select(variable) %>%
  pull() %>%
  as.vector()
  
important_variables_g2 <- all_vi_df_averaged_sam %>%
  filter(dgp_spec == "g2") %>%
  group_by(variable) %>%
  summarise(importance = mean(importance)) %>%
  arrange(desc(importance)) %>%
  ## Select the top 10
  head(10) %>%
  dplyr::select(variable) %>%
  pull() %>%
  as.vector()

important_variables_g3 <- all_vi_df_averaged_sam %>%
  filter(dgp_spec == "g3") %>%
  group_by(variable) %>%
  summarise(importance = mean(importance)) %>%
  arrange(desc(importance)) %>%
  ## Select the top 10
  head(10) %>%
  dplyr::select(variable) %>%
  pull() %>%
  as.vector()

top_model <- c("LM_MSE", "ELN_MAE", "RF_MAE", "NN5_MAE", "LSTM_MAE", "FFORMA_MSE")

all_vi_df_averaged_sam %>%
  filter(dgp_spec == "g1") %>%
  filter(model %in% top_model) %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  filter(variable %in% important_variables_g1) %>%
  ggplot() +
  geom_tile(aes(x = variable, y = model, fill = importance)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "right") +
  scale_fill_distiller(palette = "Spectral")
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/test_vi.pdf",
       width = 10 * a4_aspect_ratio, height = 10, units = "cm")

## Average variable importance over all samples

## Find the top x% of important varaibles, on average

top_variables <- all_vi_df_averaged %>%
  group_by(variable) %>%
  summarise(importance = mean(importance)) %>%
  arrange(desc(importance)) %>%
  top_n(30, importance)

top_variables <- as.character(top_variables$variable)

all_vi_df_averaged %>%
  filter(model == "LM_MSE" 
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  filter(variable %in% top_variables) %>%
  group_by(dgp_spec, model, cross_corr, variable, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, fill = importance)) +
  scale_x_discrete(label = labels, breaks = breaks) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "right") +
  scale_fill_distiller(palette = "Spectral") + 
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_ave_vi_plot_pre.pdf",
       width = 20 * a4_aspect_ratio, height = 20, units = "cm")

all_vi_df_averaged %>%
  filter(model == "NN1_MAE"
         | model == "NN2_MAE"
         | model == "NN3_MAE"
         | model == "NN4_MAE"
         | model == "NN5_MAE") %>%
  filter(variable %in% top_variables) %>%
  group_by(dgp_spec, model, cross_corr, variable, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, fill = importance)) +
  scale_x_discrete(label = labels, breaks = breaks) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "right") +
  scale_fill_distiller(palette = "Spectral") + 
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_ave_vi_plot_pre_nn.pdf",
       width = 20 * a4_aspect_ratio, height = 20, units = "cm")

all_vi_df_averaged %>%
  filter(model == "RF_MAE"
         | model == "RF_MSE") %>%
  filter(variable %in% top_variables) %>%
  group_by(dgp_spec, model, cross_corr, variable, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, fill = importance)) +
  scale_x_discrete(label = labels, breaks = breaks) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "right") +
  scale_fill_distiller(palette = "Spectral") + 
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_ave_vi_plot_pre_rf.pdf",
       width = 20 * a4_aspect_ratio, height = 20, units = "cm")

all_vi_df_averaged %>%
  filter(model == "ELN_MAE"
         | model == "ELN_MSE") %>%
  filter(variable %in% top_variables) %>%
  group_by(dgp_spec, model, cross_corr, variable, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, fill = importance)) +
  scale_x_discrete(label = labels, breaks = breaks) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "right") +
  scale_fill_distiller(palette = "Spectral") + 
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))

all_vi_df_averaged %>%
  filter(variable %in% top_variables) %>%
  group_by(dgp_spec, model, cross_corr, variable, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, fill = importance)) +
  scale_x_discrete(label = labels, breaks = breaks) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "right") +
  scale_fill_distiller(palette = "Spectral") + 
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_ave_vi_plot.pdf",
       width = 20 * a4_aspect_ratio, height = 20, units = "cm")

```

```{r hyperparam_functions}
## Plotting hyperparameters of ELN across different training samples

# Function to extract ELN hyperparameter df from simulation results list

get_eln_hyper_df <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  foreach(sample = 1:3, .combine = "rbind") %do% {
    rbind(
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "ELN_MSE",
            simulation_results_list[[realization_no]]$ELN_MSE[[sample]]$hyperparameters),
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "ELN_MAE",
            simulation_results_list[[realization_no]]$ELN_MAE[[sample]]$hyperparameters)
      )
  }
}

# Iterate this over all realizations

iterate_over_realization <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = 1:10, .combine = "rbind") %do% {
    get_eln_hyper_df(simulation_results_list, realization_no = realization_no, dgp_spec, SV, cross_corr)
  }
}

eln_hyperparameters_df <- rbind(
  iterate_over_realization(g1_A1_nosv_0_results_all, "g1", 0, 0),
  iterate_over_realization(g2_A1_nosv_0_results_all, "g2", 0, 0),
  iterate_over_realization(g3_A1_nosv_0_results_all, "g3", 0, 0),
  
  iterate_over_realization(g1_A1_sv_0.01_results_all, "g1", 1, 0.01),
  iterate_over_realization(g2_A1_sv_0.01_results_all, "g2", 1, 0.01),
  iterate_over_realization(g3_A1_sv_0.01_results_all, "g3", 1, 0.01),
  
  iterate_over_realization(g1_A1_sv_0.1_results_all, "g1", 1, 0.1),
  iterate_over_realization(g2_A1_sv_0.1_results_all, "g2", 1, 0.1),
  iterate_over_realization(g3_A1_sv_0.1_results_all, "g3", 1, 0.1),
  
  iterate_over_realization(g1_A1_sv_1_results_all, "g1", 1, 1),
  iterate_over_realization(g2_A1_sv_1_results_all, "g2", 1, 1),
  iterate_over_realization(g3_A1_sv_1_results_all, "g3", 1, 1)
)

## Alpha value plot
eln_hyperparameters_df %>%
  mutate(group_id = group_indices(., realization_no, model, dgp_spec, SV, cross_corr)) %>%
  mutate(group_id = as.factor(group_id)) %>%
  ggplot() +
  geom_line(aes(x = sample, y = alpha, group = group_id, colour = group_id)) +
  scale_x_continuous(breaks = c(1, 2, 3)) +
  theme_bw() +
  theme(legend.position = "none")
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/eln_alpha_plot.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

## Lambda Value Plot
eln_hyperparameters_df %>%
  mutate(group_id = group_indices(., realization_no, model, dgp_spec, SV, cross_corr)) %>%
  mutate(group_id = as.factor(group_id)) %>%
  ggplot() +
  geom_line(aes(x = sample, y = lambda, group = group_id, colour = group_id)) +
  scale_x_continuous(breaks = c(1, 2, 3)) +
  theme_bw() +
  theme(legend.position = "none")
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/eln_lambda_plot.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")
```

```{r hyperparam_plots}
## Plotting hyperparameters of randomforest across training samples

get_rf_hyper_df <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  foreach(sample = 1:3, .combine = "rbind") %do% {
    rbind(
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "RF_MSE",
            simulation_results_list[[realization_no]]$RF_MSE[[sample]]$hyperparameters),
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "RF_MAE",
            simulation_results_list[[realization_no]]$RF_MAE[[sample]]$hyperparameters)
      )
  }
}

iterate_over_realization <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = 1:10, .combine = "rbind") %do% {
    get_rf_hyper_df(simulation_results_list, realization_no = realization_no, dgp_spec, SV, cross_corr)
  }
}

rf_hyperparameters_df <- rbind(
  iterate_over_realization(g1_A1_nosv_0_results_all, "g1", 0, 0),
  iterate_over_realization(g2_A1_nosv_0_results_all, "g2", 0, 0),
  iterate_over_realization(g3_A1_nosv_0_results_all, "g3", 0, 0),
  
  iterate_over_realization(g1_A1_sv_0.01_results_all, "g1", 1, 0.01),
  iterate_over_realization(g2_A1_sv_0.01_results_all, "g2", 1, 0.01),
  iterate_over_realization(g3_A1_sv_0.01_results_all, "g3", 1, 0.01),
  
  iterate_over_realization(g1_A1_sv_0.1_results_all, "g1", 1, 0.1),
  iterate_over_realization(g2_A1_sv_0.1_results_all, "g2", 1, 0.1),
  iterate_over_realization(g3_A1_sv_0.1_results_all, "g3", 1, 0.1),
  
  iterate_over_realization(g1_A1_sv_1_results_all, "g1", 1, 1),
  iterate_over_realization(g2_A1_sv_1_results_all, "g2", 1, 1),
  iterate_over_realization(g3_A1_sv_1_results_all, "g3", 1, 1)
)

rf_hyperparameters_df %>%
  mutate(group_id = group_indices(., realization_no, model, dgp_spec, SV, cross_corr)) %>%
  mutate(group_id = as.factor(group_id)) %>%
  ggplot() +
  geom_line(aes(x = sample, y = mtry, group = group_id, colour = group_id)) +
  scale_x_continuous(breaks = c(1, 2, 3)) +
  theme_bw() +
  theme(legend.position = "none")
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/rf_mtry_plot.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

rf_hyperparameters_df %>%
  mutate(group_id = group_indices(., realization_no, model, dgp_spec, SV, cross_corr)) %>%
  mutate(group_id = as.factor(group_id)) %>%
  ggplot() +
  geom_line(aes(x = sample, y = nodesize, group = group_id, colour = group_id)) +
  scale_x_continuous(breaks = c(1, 2, 3)) +
  theme_bw() +
  theme(legend.position = "none")
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/rf_nodesize_plot.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")
```

