---
title: "Simulation Model Results"
author: "Ze Yu Zhong"
date: "21/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
################
##Load Libraries
################

library(tidyverse)
library(keras)
library(quantreg)
library(ggplot2)
library(forecast)
library(rlist)
library(Metrics)
library(ranger)
library(caret)
library(forcats)
library(xtable)
library(kableExtra)
library(randomForestSRC)

library(xts)
library(uwot)

#Parallel Computing
library(foreach)
library(doFuture)
#Registering
registerDoFuture()
plan(multisession)

set.seed(27935248)
```

```{r fit_all_models_function}
# Load Datasets

# Set how many realizations of datasets you wish to process
# Going with 30 for now as this is the rule of thumb for a sufficiently large sample

#batch_process_range <- c(1:30)
batch_process_range <- c(1:10)

# Actual Function
# This function takes a dataset and:
# Runs all possible models across mse and mae loss functions, does NOT save the models (for memory efficiency), and saves the loss statistics, actual forecasts, forecast residuals, and variable importance metrics into a list object
# Fairly straightforward, as the model_fit functions from before do everything for you already
# Ie acts as a very big wrapper/for loop
# Note that a lot number of the models are not multithreaded

fit_all_models <- function(dataset_list, batch_process_range,
                           # Logical arguments specifying which models you want to fit
                           # This is useful if you don't want to fit some of the most intensive methods such as RF and Neural Networks
                           LM, ELN, RF, NNet) {
  # Initialize List
  simulation_results_list <- rep(list(0), length(batch_process_range))
  
  for (batch in (batch_process_range)) {
    
    simulation_results_list[[batch]] <- list(
      # Panel Statistics
      Dataset_stats = 0, 
      # Models
      LM_MSE = 0, LM_MAE = 0,
      ELN_MSE = 0, ELN_MAE = 0,
      RF_MSE = 0, RF_MAE = 0,
      # Neural Networks
      NN1_MSE = 0, NN1_MAE = 0,
      NN2_MSE = 0, NN2_MAE = 0,
      NN3_MSE = 0, NN3_MAE = 0,
      NN4_MSE = 0, NN4_MAE = 0,
      NN5_MSE = 0, NN5_MAE = 0
    )
    
    # Load Dataset
    pooled_panel <- dataset_list[[batch]]$panel
    simulation_results_list[[batch]]$Dataset_stats <- dataset_list[[batch]]$statistics
    simulation_results_list[[batch]]$returns <- pooled_panel$rt
    
    timeSlices <- customTimeSlices(start = 2, initialWindow = 84, horizon = 12, validation_size = 60, test_size = 12, set_no = 3)
    
    f <- panel_formula(pooled_panel)
    
    if (LM == 1) {
      # Linear Models
      simulation_results_list[[batch]]$LM_MSE <- LM_fit(pooled_panel, timeSlices, "mse", f)
      simulation_results_list[[batch]]$LM_MAE <- LM_fit(pooled_panel, timeSlices, "mae", f)
    }
    
    if (ELN == 1) {
      # Penalized Linear Models
    
      alpha_grid <- seq(0, 1, 0.01)
      
      simulation_results_list[[batch]]$ELN_MAE <- ELN_fit_stats(alpha_grid, nlamb = 100, timeSlices, pooled_panel, loss_function = "mae")
      simulation_results_list[[batch]]$ELN_MSE <- ELN_fit_stats(alpha_grid, nlamb = 100, timeSlices, pooled_panel, loss_function = "mse")
    }
    
    if (RF == 1) {
      # Random Forests
      RF_grid <- expand.grid(
      #ntree usually isn't tuned. Just set to max of computationally feasible
      ntree = 50,
      mtry = seq(10, ncol(pooled_panel[4:ncol(pooled_panel)])/4, 10),
      nodesize = seq(9, 15, 3)
      # nodedepth recommended not to be changed
      #nodedepth = 1
      )
    
      simulation_results_list[[batch]]$RF_MSE <- RF_fit_stats(pooled_panel, RF_grid, timeSlices, "mse", f)
      simulation_results_list[[batch]]$RF_MAE <- RF_fit_stats(pooled_panel, RF_grid, timeSlices, "mae", f)
    }
      
    if (NNet == 1) {
      # Neural Networks
      # Commented for now because honours lab computers don't have keras/tensorflow
      
      batch_size <- 128
      patience <- 40
      
      simulation_results_list[[batch]]$NN1_MSE <- NNet_fit_stats(pooled_panel, timeSlices, 1, "mse", batch_size = batch_size, patience = patience)
      simulation_results_list[[batch]]$NN1_MAE <- NNet_fit_stats(pooled_panel, timeSlices, 1, "mae", batch_size = batch_size, patience = patience)
    
      simulation_results_list[[batch]]$NN2_MSE <- NNet_fit_stats(pooled_panel, timeSlices, 2, "mse", batch_size = batch_size, patience = patience)
      simulation_results_list[[batch]]$NN2_MAE <- NNet_fit_stats(pooled_panel, timeSlices, 2, "mae", batch_size = batch_size, patience = patience)
    
      simulation_results_list[[batch]]$NN3_MSE <- NNet_fit_stats(pooled_panel, timeSlices, 3, "mse", batch_size = batch_size, patience = patience)
      simulation_results_list[[batch]]$NN3_MAE <- NNet_fit_stats(pooled_panel, timeSlices, 3, "mae", batch_size = batch_size, patience = patience)
    
      simulation_results_list[[batch]]$NN4_MSE <- NNet_fit_stats(pooled_panel, timeSlices, 4, "mse", batch_size = batch_size, patience = patience)
      simulation_results_list[[batch]]$NN4_MAE <- NNet_fit_stats(pooled_panel, timeSlices, 4, "mae", batch_size = batch_size, patience = patience)
    
      simulation_results_list[[batch]]$NN5_MSE <- NNet_fit_stats(pooled_panel, timeSlices, 5, "mse", batch_size = batch_size, patience = patience)
      simulation_results_list[[batch]]$NN5_MAE <- NNet_fit_stats(pooled_panel, timeSlices, 5, "mae", batch_size = batch_size, patience = patience)
    }
  }
  simulation_results_list
}
```

```{r lstm_fit_all_models}
## LSTM Fit all models
fit_all_models_lstm <- function(dataset_list, batch_process_range) {
  # Initialize List
  simulation_results_list <- rep(list(0), length(batch_process_range))
  
  for (batch in (batch_process_range)) {
    
    simulation_results_list[[batch]] <- list(
      # Panel Statistics
      Dataset_stats = 0, 
      # Models
      LSTM_MSE = 0, LSTM_MAE = 0
    )
    
    # Load Dataset
    pooled_panel <- dataset_list[[batch]]$panel
    simulation_results_list[[batch]]$Dataset_stats <- dataset_list[[batch]]$statistics
    simulation_results_list[[batch]]$returns <- pooled_panel$rt
    
    timeSlices <- customTimeSlices(start = 2, initialWindow = 84, horizon = 12, validation_size = 60, test_size = 12, set_no = 3)
    
    simulation_results_list[[batch]]$LSTM_MSE <- LSTM_fit_stats(pooled_panel, timeSlices, "mse", batch_size = 64, patience = 20)
    simulation_results_list[[batch]]$LSTM_MAE <- LSTM_fit_stats(pooled_panel, timeSlices, "mae", batch_size = 64, patience = 20)
  }
  simulation_results_list
}
```

```{r fforma_fit_all_models}
## FFORMA fit all models
fit_all_models_fforma <- function(dataset_list, batch_process_range) {
  # Initialize List
  simulation_results_list <- rep(list(0), length(batch_process_range))
  
  for (batch in (batch_process_range)) {
    
    simulation_results_list[[batch]] <- list(
      # Panel Statistics
      Dataset_stats = 0, 
      # Models
      FFORMA_MSE = 0, FFORMA_MAE = 0
    )
    
    # Load Dataset
    pooled_panel <- dataset_list[[batch]]$panel
    simulation_results_list[[batch]]$Dataset_stats <- dataset_list[[batch]]$statistics
    simulation_results_list[[batch]]$returns <- pooled_panel$rt
    
    timeSlices <- customTimeSlices(start = 2, initialWindow = 84, horizon = 12, validation_size = 60, test_size = 12, set_no = 3)
    
    simulation_results_list[[batch]]$FFORMA_MSE <- fforma_fit_stats(pooled_panel, timeSlices, "mse")
    simulation_results_list[[batch]]$FFORMA_MAE <- fforma_fit_stats(pooled_panel, timeSlices, "mae")
  }
  simulation_results_list
}
```

```{r load_simulated_datasets}
## Chunk to load in simulated datasets
g1_A1_nosv_0 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g1_A1_nosv_0.RDS")
g2_A1_nosv_0 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g2_A1_nosv_0.RDS")
g3_A1_nosv_0 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g3_A1_nosv_0.RDS")
#######
g1_A1_sv_0.01 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g1_A1_sv_0.01.RDS")
g2_A1_sv_0.01 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g2_A1_sv_0.01.RDS")
g3_A1_sv_0.01 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g3_A1_sv_0.01.RDS")
#######
g1_A1_sv_0.1 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g1_A1_sv_0.1.RDS")
g2_A1_sv_0.1 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g2_A1_sv_0.1.RDS")
g3_A1_sv_0.1 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g3_A1_sv_0.1.RDS")
#######
g1_A1_sv_1 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g1_A1_sv_1.RDS")
g2_A1_sv_1 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g2_A1_sv_1.RDS")
g3_A1_sv_1 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Simulated_dataset/g3_A1_sv_1.RDS")
```

```{r lm_eln_model_fitting}
batch_process_range <- c(1:10)

# Linear and ELN Models

g1_A1_nosv_0_results <- fit_all_models(g1_A1_nosv_0, batch_process_range, LM = 1, ELN = 1, RF = 0, NNet = 0)
g2_A1_nosv_0_results <- fit_all_models(g2_A1_nosv_0, batch_process_range, LM = 1, ELN = 1, RF = 0, NNet = 0)
g3_A1_nosv_0_results <- fit_all_models(g3_A1_nosv_0, batch_process_range, LM = 1, ELN = 1, RF = 0, NNet = 0)

saveRDS(g1_A1_nosv_0_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_results.rds")
saveRDS(g2_A1_nosv_0_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_results.rds")
saveRDS(g3_A1_nosv_0_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_results.rds")

####
## RF Models
############################################################################################################

g1_A1_nosv_0_RF_results <- fit_all_models(g1_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g1_A1_nosv_0_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_RF_results.rds")
g2_A1_nosv_0_RF_results <- fit_all_models(g2_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g2_A1_nosv_0_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_RF_results.rds")
g3_A1_nosv_0_RF_results <- fit_all_models(g3_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g3_A1_nosv_0_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_RF_results.rds")

g1_A1_nosv_0_NN_results <- fit_all_models(g1_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_nosv_0_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_NN_results.rds")
g2_A1_nosv_0_NN_results <- fit_all_models(g2_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_nosv_0_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_NN_results.rds")
g3_A1_nosv_0_NN_results <- fit_all_models(g3_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_nosv_0_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_NN_results.rds")

#############################################################################################################

g1_A1_sv_0.01_results <- fit_all_models(g1_A1_sv_0.01, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)
g2_A1_sv_0.01_results <- fit_all_models(g2_A1_sv_0.01, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)
g3_A1_sv_0.01_results <- fit_all_models(g3_A1_sv_0.01, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)

saveRDS(g1_A1_sv_0.01_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_results.rds")
saveRDS(g2_A1_sv_0.01_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_results.rds")
saveRDS(g3_A1_sv_0.01_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_results.rds")

g1_A1_sv_0.01_RF_results <- fit_all_models(g1_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g1_A1_sv_0.01_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_RF_results.rds")
g2_A1_sv_0.01_RF_results <- fit_all_models(g2_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g2_A1_sv_0.01_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_RF_results.rds")
g3_A1_sv_0.01_RF_results <- fit_all_models(g3_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g3_A1_sv_0.01_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_RF_results.rds")

g1_A1_sv_0.01_NN_results <- fit_all_models(g1_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_0.01_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_NN_results.rds")
g2_A1_sv_0.01_NN_results <- fit_all_models(g2_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_0.01_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_NN_results.rds")
g3_A1_sv_0.01_NN_results <- fit_all_models(g3_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_0.01_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_NN_results.rds")

#############################################################################################################

g1_A1_sv_0.1_results <- fit_all_models(g1_A1_sv_0.1, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)
g2_A1_sv_0.1_results <- fit_all_models(g2_A1_sv_0.1, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)
g3_A1_sv_0.1_results <- fit_all_models(g3_A1_sv_0.1, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)

saveRDS(g1_A1_sv_0.1_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_results.rds")
saveRDS(g2_A1_sv_0.1_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_results.rds")
saveRDS(g3_A1_sv_0.1_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_results.rds")

g1_A1_sv_0.1_RF_results <- fit_all_models(g1_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g1_A1_sv_0.1_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_RF_results.rds")
g2_A1_sv_0.1_RF_results <- fit_all_models(g2_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g2_A1_sv_0.1_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_RF_results.rds")
g3_A1_sv_0.1_RF_results <- fit_all_models(g3_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g3_A1_sv_0.1_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_RF_results.rds")

g1_A1_sv_0.1_NN_results <- fit_all_models(g1_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_0.1_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_NN_results.rds")
g2_A1_sv_0.1_NN_results <- fit_all_models(g2_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_0.1_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_NN_results.rds")
g3_A1_sv_0.1_NN_results <- fit_all_models(g3_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_0.1_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_NN_results.rds")

#############################################################################################################

g1_A1_sv_1_results <- fit_all_models(g1_A1_sv_1, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)
g2_A1_sv_1_results <- fit_all_models(g2_A1_sv_1, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)
g3_A1_sv_1_results <- fit_all_models(g3_A1_sv_1, batch_process_range, LM = 1, ELN = 1, RF = 1, NNet = 0)

saveRDS(g1_A1_sv_1_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_results.rds")
saveRDS(g2_A1_sv_1_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_results.rds")
saveRDS(g3_A1_sv_1_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_results.rds")

g1_A1_sv_1_RF_results <- fit_all_models(g1_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g1_A1_sv_1_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_RF_results.rds")
g2_A1_sv_1_RF_results <- fit_all_models(g2_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g2_A1_sv_1_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_RF_results.rds")
g3_A1_sv_1_RF_results <- fit_all_models(g3_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 1, NNet = 0)
saveRDS(g3_A1_sv_1_RF_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_RF_results.rds")

g1_A1_sv_1_NN_results <- fit_all_models(g1_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_1_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_NN_results.rds")
g2_A1_sv_1_NN_results <- fit_all_models(g2_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_1_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_NN_results.rds")
g3_A1_sv_1_NN_results <- fit_all_models(g3_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_1_NN_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_NN_results.rds")
```

```{r mlp_fitting_1_5}
## MLPs for datasets 1-5
batch_process_range <- c(1:5)

g1_A1_nosv_0_NN_results15 <- fit_all_models(g1_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_nosv_0_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_NN_results15.rds")
g2_A1_nosv_0_NN_results15 <- fit_all_models(g2_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_nosv_0_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_NN_results15.rds")
g3_A1_nosv_0_NN_results15 <- fit_all_models(g3_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_nosv_0_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_NN_results15.rds")

g1_A1_sv_0.01_NN_results15 <- fit_all_models(g1_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_0.01_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_NN_results15.rds")
g2_A1_sv_0.01_NN_results15 <- fit_all_models(g2_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_0.01_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_NN_results15.rds")
g3_A1_sv_0.01_NN_results15 <- fit_all_models(g3_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_0.01_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_NN_results15.rds")

g1_A1_sv_0.1_NN_results15 <- fit_all_models(g1_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_0.1_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_NN_results15.rds")
g2_A1_sv_0.1_NN_results15 <- fit_all_models(g2_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_0.1_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_NN_results15.rds")
g3_A1_sv_0.1_NN_results15 <- fit_all_models(g3_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_0.1_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_NN_results15.rds")

g1_A1_sv_1_NN_results15 <- fit_all_models(g1_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_1_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_NN_results15.rds")
g2_A1_sv_1_NN_results15 <- fit_all_models(g2_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_1_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_NN_results15.rds")
g3_A1_sv_1_NN_results15 <- fit_all_models(g3_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_1_NN_results15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_NN_results15.rds")
```

```{r mlp_fitting_6_10}
## MLPs for datasets 6-10
batch_process_range <- c(6:10)

g1_A1_nosv_0_NN_results610 <- fit_all_models(g1_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_nosv_0_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_NN_results610.rds")
g2_A1_nosv_0_NN_results610 <- fit_all_models(g2_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_nosv_0_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_NN_results610.rds")
g3_A1_nosv_0_NN_results610 <- fit_all_models(g3_A1_nosv_0, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_nosv_0_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_NN_results610.rds")

g1_A1_sv_0.01_NN_results610 <- fit_all_models(g1_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_0.01_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_NN_results610.rds")
g2_A1_sv_0.01_NN_results610 <- fit_all_models(g2_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_0.01_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_NN_results610.rds")
g3_A1_sv_0.01_NN_results610 <- fit_all_models(g3_A1_sv_0.01, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_0.01_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_NN_results610.rds")

g1_A1_sv_0.1_NN_results610 <- fit_all_models(g1_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_0.1_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_NN_results610.rds")
g2_A1_sv_0.1_NN_results610 <- fit_all_models(g2_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_0.1_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_NN_results610.rds")
g3_A1_sv_0.1_NN_results610 <- fit_all_models(g3_A1_sv_0.1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_0.1_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_NN_results610.rds")

g1_A1_sv_1_NN_results610 <- fit_all_models(g1_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g1_A1_sv_1_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_NN_results610.rds")
g2_A1_sv_1_NN_results610 <- fit_all_models(g2_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g2_A1_sv_1_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_NN_results610.rds")
g3_A1_sv_1_NN_results610 <- fit_all_models(g3_A1_sv_1, batch_process_range, LM = 0, ELN = 0, RF = 0, NNet = 1)
saveRDS(g3_A1_sv_1_NN_results610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_NN_results610.rds")
```

```{r fitting_lstm_models_15}
batch_process_range <- c(1:5)

g1_A1_nosv_0_LSTM_results_15 <- fit_all_models_lstm(g1_A1_nosv_0, batch_process_range)
saveRDS(g1_A1_nosv_0_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_LSTM_results_15.rds")
g2_A1_nosv_0_LSTM_results_15 <- fit_all_models_lstm(g2_A1_nosv_0, batch_process_range)
saveRDS(g2_A1_nosv_0_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_LSTM_results_15.rds")
g3_A1_nosv_0_LSTM_results_15 <- fit_all_models_lstm(g3_A1_nosv_0, batch_process_range)
saveRDS(g3_A1_nosv_0_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_LSTM_results_15.rds")

g1_A1_sv_0.01_LSTM_results_15 <- fit_all_models_lstm(g1_A1_sv_0.01, batch_process_range)
saveRDS(g1_A1_sv_0.01_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_LSTM_results_15.rds")
g2_A1_sv_0.01_LSTM_results_15 <- fit_all_models_lstm(g2_A1_sv_0.01, batch_process_range)
saveRDS(g2_A1_sv_0.01_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_LSTM_results_15.rds")
g3_A1_sv_0.01_LSTM_results_15 <- fit_all_models_lstm(g3_A1_sv_0.01, batch_process_range)
saveRDS(g3_A1_sv_0.01_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_LSTM_results_15.rds")

g1_A1_sv_0.1_LSTM_results_15 <- fit_all_models_lstm(g1_A1_sv_0.1, batch_process_range)
saveRDS(g1_A1_sv_0.1_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_LSTM_results_15.rds")
g2_A1_sv_0.1_LSTM_results_15 <- fit_all_models_lstm(g2_A1_sv_0.1, batch_process_range)
saveRDS(g2_A1_sv_0.1_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_LSTM_results_15.rds")
g3_A1_sv_0.1_LSTM_results_15 <- fit_all_models_lstm(g3_A1_sv_0.1, batch_process_range)
saveRDS(g3_A1_sv_0.1_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_LSTM_results_15.rds")

g1_A1_sv_1_LSTM_results_15 <- fit_all_models_lstm(g1_A1_sv_1, batch_process_range)
saveRDS(g1_A1_sv_1_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_LSTM_results_15.rds")
g2_A1_sv_1_LSTM_results_15 <- fit_all_models_lstm(g2_A1_sv_1, batch_process_range)
saveRDS(g2_A1_sv_1_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_LSTM_results_15.rds")
g3_A1_sv_1_LSTM_results_15 <- fit_all_models_lstm(g3_A1_sv_1, batch_process_range)
saveRDS(g3_A1_sv_1_LSTM_results_15, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_LSTM_results_15.rds")
```

```{r fitting_lstm_models_610}
batch_process_range <- c(6:10)

g1_A1_nosv_0_LSTM_results_610 <- fit_all_models_lstm(g1_A1_nosv_0, batch_process_range)
saveRDS(g1_A1_nosv_0_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_LSTM_results_610.rds")
g2_A1_nosv_0_LSTM_results_610 <- fit_all_models_lstm(g2_A1_nosv_0, batch_process_range)
saveRDS(g2_A1_nosv_0_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_LSTM_results_610.rds")
g3_A1_nosv_0_LSTM_results_610 <- fit_all_models_lstm(g3_A1_nosv_0, batch_process_range)
saveRDS(g3_A1_nosv_0_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_LSTM_results_610.rds")

g1_A1_sv_0.01_LSTM_results_610 <- fit_all_models_lstm(g1_A1_sv_0.01, batch_process_range)
saveRDS(g1_A1_sv_0.01_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_LSTM_results_610.rds")
g2_A1_sv_0.01_LSTM_results_610 <- fit_all_models_lstm(g2_A1_sv_0.01, batch_process_range)
saveRDS(g2_A1_sv_0.01_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_LSTM_results_610.rds")
g3_A1_sv_0.01_LSTM_results_610 <- fit_all_models_lstm(g3_A1_sv_0.01, batch_process_range)
saveRDS(g3_A1_sv_0.01_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_LSTM_results_610.rds")

g1_A1_sv_0.1_LSTM_results_610 <- fit_all_models_lstm(g1_A1_sv_0.1, batch_process_range)
saveRDS(g1_A1_sv_0.1_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_LSTM_results_610.rds")
g2_A1_sv_0.1_LSTM_results_610 <- fit_all_models_lstm(g2_A1_sv_0.1, batch_process_range)
saveRDS(g2_A1_sv_0.1_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_LSTM_results_610.rds")
g3_A1_sv_0.1_LSTM_results_610 <- fit_all_models_lstm(g3_A1_sv_0.1, batch_process_range)
saveRDS(g3_A1_sv_0.1_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_LSTM_results_610.rds")

g1_A1_sv_1_LSTM_results_610 <- fit_all_models_lstm(g1_A1_sv_1, batch_process_range)
saveRDS(g1_A1_sv_1_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_LSTM_results_610.rds")
g2_A1_sv_1_LSTM_results_610 <- fit_all_models_lstm(g2_A1_sv_1, batch_process_range)
saveRDS(g2_A1_sv_1_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_LSTM_results_610.rds")
g3_A1_sv_1_LSTM_results_610 <- fit_all_models_lstm(g3_A1_sv_1, batch_process_range)
saveRDS(g3_A1_sv_1_LSTM_results_610, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_LSTM_results_610.rds")
```

```{r fitting_fforma_models}
## Fitting FFORMA Models
batch_process_range <- c(1:10)

g1_A1_nosv_0_FFORMA_results <- fit_all_models_fforma(g1_A1_nosv_0, batch_process_range)
saveRDS(g1_A1_nosv_0_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_FFORMA_results.rds")
g2_A1_nosv_0_FFORMA_results <- fit_all_models_fforma(g2_A1_nosv_0, batch_process_range)
saveRDS(g2_A1_nosv_0_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_FFORMA_results.rds")
g3_A1_nosv_0_FFORMA_results <- fit_all_models_fforma(g3_A1_nosv_0, batch_process_range)
saveRDS(g3_A1_nosv_0_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_FFORMA_results.rds")

g1_A1_sv_0.01_FFORMA_results <- fit_all_models_fforma(g1_A1_sv_0.01, batch_process_range)
saveRDS(g1_A1_sv_0.01_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_FFORMA_results.rds")
g2_A1_sv_0.01_FFORMA_results <- fit_all_models_fforma(g2_A1_sv_0.01, batch_process_range)
saveRDS(g2_A1_sv_0.01_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_FFORMA_results.rds")
g3_A1_sv_0.01_FFORMA_results <- fit_all_models_fforma(g3_A1_sv_0.01, batch_process_range)
saveRDS(g3_A1_sv_0.01_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_FFORMA_results.rds")

g1_A1_sv_0.1_FFORMA_results <- fit_all_models_fforma(g1_A1_sv_0.1, batch_process_range)
saveRDS(g1_A1_sv_0.1_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_FFORMA_results.rds")
g2_A1_sv_0.1_FFORMA_results <- fit_all_models_fforma(g2_A1_sv_0.1, batch_process_range)
saveRDS(g2_A1_sv_0.1_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_FFORMA_results.rds")
g3_A1_sv_0.1_FFORMA_results <- fit_all_models_fforma(g3_A1_sv_0.1, batch_process_range)
saveRDS(g3_A1_sv_0.1_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_FFORMA_results.rds")

g1_A1_sv_1_FFORMA_results <- fit_all_models_fforma(g1_A1_sv_1, batch_process_range)
saveRDS(g1_A1_sv_1_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_FFORMA_results.rds")
g2_A1_sv_1_FFORMA_results <- fit_all_models_fforma(g2_A1_sv_1, batch_process_range)
saveRDS(g2_A1_sv_1_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_FFORMA_results.rds")
g3_A1_sv_1_FFORMA_results <- fit_all_models_fforma(g3_A1_sv_1, batch_process_range)
saveRDS(g3_A1_sv_1_FFORMA_results, "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_FFORMA_results.rds")
```

```{r load_partial_results}
## Chunk to load all results lists

g1_A1_nosv_0_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_nosv_0_results.RDS")
g2_A1_nosv_0_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_nosv_0_results.RDS")
g3_A1_nosv_0_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_nosv_0_results.RDS")

g1_A1_sv_0.01_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_results.RDS")
g2_A1_sv_0.01_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_results.RDS")
g3_A1_sv_0.01_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_results.RDS")

g1_A1_sv_0.1_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_results.RDS")
g2_A1_sv_0.1_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_results.RDS")
g3_A1_sv_0.1_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_results.RDS")

g1_A1_sv_1_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_results.RDS")
g2_A1_sv_1_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_results.RDS")
g3_A1_sv_1_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_results.RDS")

####################################################################################################################
## Random Forests

g1_A1_nosv_0_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_nosv_0_RF_results.RDS")
g2_A1_nosv_0_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_nosv_0_RF_results.RDS")
g3_A1_nosv_0_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_nosv_0_RF_results.RDS")

g1_A1_sv_0.01_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_RF_results.RDS")
g2_A1_sv_0.01_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_RF_results.RDS")
g3_A1_sv_0.01_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_RF_results.RDS")

g1_A1_sv_0.1_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_RF_results.RDS")
g2_A1_sv_0.1_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_RF_results.RDS")
g3_A1_sv_0.1_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_RF_results.RDS")

g1_A1_sv_1_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_RF_results.RDS")
g2_A1_sv_1_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_RF_results.RDS")
g3_A1_sv_1_RF_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_RF_results.RDS")

####################################################################################################################
## MLP Results

g1_A1_nosv_0_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_nosv_0_NN_results15.RDS")
g2_A1_nosv_0_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_nosv_0_NN_results15.RDS")
g3_A1_nosv_0_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_nosv_0_NN_results15.RDS")

g1_A1_sv_0.01_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_NN_results15.RDS")
g2_A1_sv_0.01_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_NN_results15.RDS")
g3_A1_sv_0.01_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_NN_results15.RDS")

g1_A1_sv_0.1_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_NN_results15.RDS")
g2_A1_sv_0.1_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_NN_results15.RDS")
g3_A1_sv_0.1_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_NN_results15.RDS")

g1_A1_sv_1_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_NN_results15.RDS")
g2_A1_sv_1_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_NN_results15.RDS")
g3_A1_sv_1_NN_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_NN_results15.RDS")
##
g1_A1_nosv_0_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_nosv_0_NN_results610.RDS")
g2_A1_nosv_0_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_nosv_0_NN_results610.RDS")
g3_A1_nosv_0_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_nosv_0_NN_results610.RDS")

g1_A1_sv_0.01_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_NN_results610.RDS")
g2_A1_sv_0.01_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_NN_results610.RDS")
g3_A1_sv_0.01_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_NN_results610.RDS")

g1_A1_sv_0.1_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_NN_results610.RDS")
g2_A1_sv_0.1_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_NN_results610.RDS")
g3_A1_sv_0.1_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_NN_results610.RDS")

g1_A1_sv_1_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_NN_results610.RDS")
g2_A1_sv_1_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_NN_results610.RDS")
g3_A1_sv_1_NN_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_NN_results610.RDS")

#################################################################
## LSTM Results
#################################################################
g1_A1_nosv_0_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_nosv_0_LSTM_results_15.RDS")
g2_A1_nosv_0_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_nosv_0_LSTM_results_15.RDS")
g3_A1_nosv_0_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_nosv_0_LSTM_results_15.RDS")

g1_A1_sv_0.01_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_LSTM_results_15.RDS")
g2_A1_sv_0.01_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_LSTM_results_15.RDS")
g3_A1_sv_0.01_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_LSTM_results_15.RDS")

g1_A1_sv_0.1_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_LSTM_results_15.RDS")
g2_A1_sv_0.1_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_LSTM_results_15.RDS")
g3_A1_sv_0.1_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_LSTM_results_15.RDS")

g1_A1_sv_1_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_LSTM_results_15.RDS")
g2_A1_sv_1_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_LSTM_results_15.RDS")
g3_A1_sv_1_LSTM_results_15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_LSTM_results_15.RDS")
#################################################################
## These are pending atm
g1_A1_nosv_0_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_nosv_0_LSTM_results_610.RDS")
g2_A1_nosv_0_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_nosv_0_LSTM_results_610.RDS")
g3_A1_nosv_0_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_nosv_0_LSTM_results_610.RDS")

g1_A1_sv_0.01_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_LSTM_results_610.RDS")
g2_A1_sv_0.01_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_LSTM_results_610.RDS")
g3_A1_sv_0.01_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_LSTM_results_610.RDS")

g1_A1_sv_0.1_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_LSTM_results_610.RDS")
g2_A1_sv_0.1_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_LSTM_results_610.RDS")
g3_A1_sv_0.1_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_LSTM_results_610.RDS")

g1_A1_sv_1_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_LSTM_results_610.RDS")
g2_A1_sv_1_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_LSTM_results_610.RDS")
g3_A1_sv_1_LSTM_results_610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_LSTM_results_610.RDS")

#################################################################
## FFORMA
#################################################################

g1_A1_nosv_0_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_nosv_0_FFORMA_results.RDS")
g2_A1_nosv_0_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_nosv_0_FFORMA_results.RDS")
g3_A1_nosv_0_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_nosv_0_FFORMA_results.RDS")

g1_A1_sv_0.01_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_FFORMA_results.RDS")
g2_A1_sv_0.01_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_FFORMA_results.RDS")
g3_A1_sv_0.01_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_FFORMA_results.RDS")

g1_A1_sv_0.1_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_FFORMA_results.RDS")
g2_A1_sv_0.1_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_FFORMA_results.RDS")
g3_A1_sv_0.1_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_FFORMA_results.RDS")

g1_A1_sv_1_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_FFORMA_results.RDS")
g2_A1_sv_1_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_FFORMA_results.RDS")
g3_A1_sv_1_FFORMA_results <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_FFORMA_results.RDS")

#################################################################
## AWS DEEPAR
#################################################################

## Change format function

deepar_change_format15 <- function(deepar_list_15) {
  for (i in 1:5) {
    for (set in 1:3) {
      deepar_list_15[[i]]$DEEPAR_MSE[[set]]$loss_stats <- deepar_list_15[[i]]$DEEPAR_MSE[[set]]$loss_stats %>%
        mutate(train_RSquare = train_Rsquare) %>%
        dplyr::select(train_MAE, train_MSE, train_RMSE, train_RSquare, 
                      validation_MAE, validation_MSE, validation_RMSE, validation_RSquare,
                      test_MAE, test_MSE, test_RMSE, test_RSquare)
    }
  }
  deepar_list_15
}

deepar_change_format610 <- function(deepar_list_610) {
  for (i in 6:10) {
    for (set in 1:3) {
      deepar_list_610[[i]]$DEEPAR_MSE[[set]]$loss_stats <- deepar_list_610[[i]]$DEEPAR_MSE[[set]]$loss_stats %>%
        mutate(train_RSquare = train_Rsquare) %>%
        dplyr::select(train_MAE, train_MSE, train_RMSE, train_RSquare, 
                      validation_MAE, validation_MSE, validation_RMSE, validation_RSquare,
                      test_MAE, test_MSE, test_RMSE, test_RSquare)
    }
  }
  deepar_list_610
}

g1_A1_sv_0.01_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g1_A1_sv_0.01_DeepAR_results15.rds")

g2_A1_sv_0.01_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g2_A1_sv_0.01_DeepAR_results15.rds")

g3_A1_sv_0.01_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g3_A1_sv_0.01_DeepAR_results15.rds")

g1_A1_sv_0.1_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g1_A1_sv_0.1_DeepAR_results15.rds")

g2_A1_sv_0.1_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g2_A1_sv_0.1_DeepAR_results15.rds")

g3_A1_sv_0.1_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g3_A1_sv_0.1_DeepAR_results15.rds")

g1_A1_sv_1_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g1_A1_sv_1_DeepAR_results15.rds")

g2_A1_sv_1_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g2_A1_sv_1_DeepAR_results15.rds")

g3_A1_sv_1_DeepAR_results15 %>%
  deepar_change_format15 %>%
  saveRDS("g3_A1_sv_1_DeepAR_results15.rds")

g1_A1_sv_0.01_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g1_A1_sv_0.01_DeepAR_results610.rds")

g2_A1_sv_0.01_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g2_A1_sv_0.01_DeepAR_results610.rds")

g3_A1_sv_0.01_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g3_A1_sv_0.01_DeepAR_results610.rds")

g1_A1_sv_0.1_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g1_A1_sv_0.1_DeepAR_results610.rds")

g2_A1_sv_0.1_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g2_A1_sv_0.1_DeepAR_results610.rds")

g3_A1_sv_0.1_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g3_A1_sv_0.1_DeepAR_results610.rds")

g1_A1_sv_1_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g1_A1_sv_1_DeepAR_results610.rds")

g2_A1_sv_1_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g2_A1_sv_1_DeepAR_results610.rds")

g3_A1_sv_1_DeepAR_results610 %>%
  deepar_change_format610 %>%
  saveRDS("g3_A1_sv_1_DeepAR_results610.rds")


g1_A1_sv_0.01_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_DeepAR_results15.RDS")
g2_A1_sv_0.01_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_DeepAR_results15.RDS")
g3_A1_sv_0.01_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_DeepAR_results15.RDS")

g1_A1_sv_0.1_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_DeepAR_results15.RDS")
g2_A1_sv_0.1_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_DeepAR_results15.RDS")
g3_A1_sv_0.1_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_DeepAR_results15.RDS")

g1_A1_sv_1_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_DeepAR_results15.RDS")
g2_A1_sv_1_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_DeepAR_results15.RDS")
g3_A1_sv_1_DeepAR_results15 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_DeepAR_results15.RDS")

#########################################################################################

g1_A1_sv_0.01_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.01_DeepAR_results610.RDS")
g2_A1_sv_0.01_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.01_DeepAR_results610.RDS")
g3_A1_sv_0.01_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.01_DeepAR_results610.RDS")

g1_A1_sv_0.1_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_0.1_DeepAR_results610.RDS")
g2_A1_sv_0.1_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_0.1_DeepAR_results610.RDS")
g3_A1_sv_0.1_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_0.1_DeepAR_results610.RDS")

g1_A1_sv_1_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g1_A1_sv_1_DeepAR_results610.RDS")
g2_A1_sv_1_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g2_A1_sv_1_DeepAR_results610.RDS")
g3_A1_sv_1_DeepAR_results610 <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/simulation/g3_A1_sv_1_DeepAR_results610.RDS")

```

```{r combine_results}
## Combining the results together

## Combine the RF results together first

combine_RF_results_list <- function(normal_list, RF_list) {
  for(i in 1:10) {
    normal_list[[i]]$RF_MSE <- RF_list[[i]]$RF_MSE
    normal_list[[i]]$RF_MAE <- RF_list[[i]]$RF_MAE
  }
  normal_list
}

## Combine the NN results together

combine_NN_results_list <- function(normal_list, nn15_list, nn610_list) {
  for(i in 1:5) {
    normal_list[[i]]$NN1_MSE <- nn15_list[[i]]$NN1_MSE
    normal_list[[i]]$NN1_MAE <- nn15_list[[i]]$NN1_MAE
    
    normal_list[[i]]$NN2_MSE <- nn15_list[[i]]$NN2_MSE
    normal_list[[i]]$NN2_MAE <- nn15_list[[i]]$NN2_MAE
    
    normal_list[[i]]$NN3_MSE <- nn15_list[[i]]$NN3_MSE
    normal_list[[i]]$NN3_MAE <- nn15_list[[i]]$NN3_MAE
    
    normal_list[[i]]$NN4_MSE <- nn15_list[[i]]$NN4_MSE
    normal_list[[i]]$NN4_MAE <- nn15_list[[i]]$NN4_MAE
    
    normal_list[[i]]$NN5_MSE <- nn15_list[[i]]$NN5_MSE
    normal_list[[i]]$NN5_MAE <- nn15_list[[i]]$NN5_MAE
  }
  
  for(i in 6:10) {
    normal_list[[i]]$NN1_MSE <- nn610_list[[i]]$NN1_MSE
    normal_list[[i]]$NN1_MAE <- nn610_list[[i]]$NN1_MAE
    
    normal_list[[i]]$NN2_MSE <- nn610_list[[i]]$NN2_MSE
    normal_list[[i]]$NN2_MAE <- nn610_list[[i]]$NN2_MAE
    
    normal_list[[i]]$NN3_MSE <- nn610_list[[i]]$NN3_MSE
    normal_list[[i]]$NN3_MAE <- nn610_list[[i]]$NN3_MAE
    
    normal_list[[i]]$NN4_MSE <- nn610_list[[i]]$NN4_MSE
    normal_list[[i]]$NN4_MAE <- nn610_list[[i]]$NN4_MAE
    
    normal_list[[i]]$NN5_MSE <- nn610_list[[i]]$NN5_MSE
    normal_list[[i]]$NN5_MAE <- nn610_list[[i]]$NN5_MAE
  }
  normal_list
}

## Combining LSTM Results

combine_LSTM_results_list <- function(normal_list, lstm15_list, lstm_610_list) {
  for (i in 1:5) {
    normal_list[[i]]$LSTM_MSE <- lstm15_list[[i]]$LSTM_MSE
    normal_list[[i]]$LSTM_MAE <- lstm15_list[[i]]$LSTM_MAE
  }
  
  ## Coment 6-10 for now
  
  # for (i in 6:10) {
  #   normal_list[[i]]$LSTM_MSE <- lstm610_list[[i]]$LSTM_MSE
  #   normal_list[[i]]$LSTM_MAE <- lstm610_list[[i]]$LSTM_MAE
  # }
  normal_list
}


## Combining FFORMA Results
combine_FFORMA_results_list <- function(normal_list, fforma_list) {
  for(i in 1:10) {
    normal_list[[i]]$FFORMA_MSE <- fforma_list[[i]]$FFORMA_MSE
    normal_list[[i]]$FFORMA_MAE <- fforma_list[[i]]$FFORMA_MAE
    
    normal_list[[i]]$FFORMA_MSE <- fforma_list[[i]]$FFORMA_MSE
    normal_list[[i]]$FFORMA_MAE <- fforma_list[[i]]$FFORMA_MAE
    
    normal_list[[i]]$FFORMA_MSE <- fforma_list[[i]]$FFORMA_MSE
    normal_list[[i]]$FFORMA_MAE <- fforma_list[[i]]$FFORMA_MAE
    
    normal_list[[i]]$FFORMA_MSE <- fforma_list[[i]]$FFORMA_MSE
    normal_list[[i]]$FFORMA_MAE <- fforma_list[[i]]$FFORMA_MAE
    
    normal_list[[i]]$FFORMA_MSE <- fforma_list[[i]]$FFORMA_MSE
    normal_list[[i]]$FFORMA_MAE <- fforma_list[[i]]$FFORMA_MAE
  }
  normal_list
}

## Combining DeepAR Results

combine_DeepAR_results_list <- function(normal_list, deepar_list15, deepar_list610) {
  for(i in 1:5) {
    normal_list[[i]]$DeepAR <- deepar_list15[[i]]$DEEPAR_MSE
  }
  for(i in 6:10) {
    normal_list[[i]]$DeepAR <- deepar_list610[[i]]$DEEPAR_MSE
  }
  normal_list
}

## nosv_0
## Don't bother with this design because it's stupid, and was only done just to replicate Gu's experiments
# g1_A1_nosv_0_results_all <- g1_A1_nosv_0_results %>% 
#   combine_RF_results_list(g1_A1_nosv_0_RF_results) %>%
#   combine_NN_results_list(g1_A1_nosv_0_NN_results15, g1_A1_nosv_0_NN_results610) %>%
#   combine_LSTM_results_list(g1_A1_nosv_0_LSTM_results_15, 0) %>%
#   combine_FFORMA_results_list(g1_A1_nosv_0_FFORMA_results) %>%
#   combine_DeepAR_results_list(g1_A1_nosv)
# g2_A1_nosv_0_results_all <- g2_A1_nosv_0_results %>% 
#   combine_RF_results_list(g2_A1_nosv_0_RF_results) %>%
#   combine_NN_results_list(g2_A1_nosv_0_NN_results15, g2_A1_nosv_0_NN_results610) %>%
#   combine_LSTM_results_list(g2_A1_nosv_0_LSTM_results_15, 0) %>%
#   combine_FFORMA_results_list(g2_A1_nosv_0_FFORMA_results)
# g3_A1_nosv_0_results_all <- g3_A1_nosv_0_results %>% 
#   combine_RF_results_list(g3_A1_nosv_0_RF_results) %>%
#   combine_NN_results_list(g3_A1_nosv_0_NN_results15, g3_A1_nosv_0_NN_results610) %>%
#   combine_LSTM_results_list(g3_A1_nosv_0_LSTM_results_15, 0) %>%
#   combine_FFORMA_results_list(g3_A1_nosv_0_FFORMA_results)
## sv_0.01
g1_A1_sv_0.01_results_all <- g1_A1_sv_0.01_results %>% 
  combine_RF_results_list(g1_A1_sv_0.01_RF_results) %>%
  combine_NN_results_list(g1_A1_sv_0.01_NN_results15, g1_A1_sv_0.01_NN_results610) %>%
  combine_LSTM_results_list(g1_A1_sv_0.01_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g1_A1_sv_0.01_FFORMA_results) %>%
  combine_DeepAR_results_list(g1_A1_sv_0.01_DeepAR_results15, g1_A1_sv_0.01_DeepAR_results610)
g2_A1_sv_0.01_results_all <- g2_A1_sv_0.01_results %>% 
  combine_RF_results_list(g2_A1_sv_0.01_RF_results) %>%
  combine_NN_results_list(g2_A1_sv_0.01_NN_results15, g2_A1_sv_0.01_NN_results610) %>%
  combine_LSTM_results_list(g2_A1_sv_0.01_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g2_A1_sv_0.01_FFORMA_results) %>%
  combine_DeepAR_results_list(g2_A1_sv_0.01_DeepAR_results15, g2_A1_sv_0.01_DeepAR_results610)
g3_A1_sv_0.01_results_all <- g3_A1_sv_0.01_results %>% 
  combine_RF_results_list(g3_A1_sv_0.01_RF_results) %>%
  combine_NN_results_list(g3_A1_sv_0.01_NN_results15, g3_A1_sv_0.01_NN_results610) %>%
  combine_LSTM_results_list(g3_A1_sv_0.01_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g3_A1_sv_0.01_FFORMA_results) %>%
  combine_DeepAR_results_list(g3_A1_sv_0.01_DeepAR_results15, g3_A1_sv_0.01_DeepAR_results610)
## sv_0.1
g1_A1_sv_0.1_results_all <- g1_A1_sv_0.1_results %>% 
  combine_RF_results_list(g1_A1_sv_0.1_RF_results) %>%
  combine_NN_results_list(g1_A1_sv_0.1_NN_results15, g1_A1_sv_0.1_NN_results610) %>%
  combine_LSTM_results_list(g1_A1_sv_0.1_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g1_A1_sv_0.1_FFORMA_results) %>%
  combine_DeepAR_results_list(g1_A1_sv_0.1_DeepAR_results15, g1_A1_sv_0.1_DeepAR_results610)
g2_A1_sv_0.1_results_all <- g2_A1_sv_0.1_results %>% 
  combine_RF_results_list(g2_A1_sv_0.1_RF_results) %>%
  combine_NN_results_list(g2_A1_sv_0.1_NN_results15, g2_A1_sv_0.1_NN_results610) %>%
  combine_LSTM_results_list(g2_A1_sv_0.1_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g2_A1_sv_0.1_FFORMA_results) %>%
  combine_DeepAR_results_list(g2_A1_sv_0.1_DeepAR_results15, g2_A1_sv_0.1_DeepAR_results610)
g3_A1_sv_0.1_results_all <- g3_A1_sv_0.1_results %>% 
  combine_RF_results_list(g3_A1_sv_0.1_RF_results) %>%
  combine_NN_results_list(g3_A1_sv_0.1_NN_results15, g3_A1_sv_0.1_NN_results610) %>%
  combine_LSTM_results_list(g3_A1_sv_0.1_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g3_A1_sv_0.1_FFORMA_results) %>%
  combine_DeepAR_results_list(g3_A1_sv_0.1_DeepAR_results15, g3_A1_sv_0.1_DeepAR_results610)
## sv_1
g1_A1_sv_1_results_all <- g1_A1_sv_1_results %>% 
  combine_RF_results_list(g1_A1_sv_1_RF_results) %>%
  combine_NN_results_list(g1_A1_sv_1_NN_results15, g1_A1_sv_1_NN_results610)%>%
  combine_LSTM_results_list(g1_A1_sv_1_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g1_A1_sv_1_FFORMA_results) %>%
  combine_DeepAR_results_list(g1_A1_sv_1_DeepAR_results15, g1_A1_sv_1_DeepAR_results610)
g2_A1_sv_1_results_all <- g2_A1_sv_1_results %>% 
  combine_RF_results_list(g2_A1_sv_1_RF_results) %>%
  combine_NN_results_list(g2_A1_sv_1_NN_results15, g2_A1_sv_1_NN_results610)%>%
  combine_LSTM_results_list(g2_A1_sv_1_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g2_A1_sv_1_FFORMA_results) %>%
  combine_DeepAR_results_list(g2_A1_sv_1_DeepAR_results15, g2_A1_sv_1_DeepAR_results610)
g3_A1_sv_1_results_all <- g3_A1_sv_1_results %>% 
  combine_RF_results_list(g3_A1_sv_1_RF_results) %>%
  combine_NN_results_list(g3_A1_sv_1_NN_results15, g3_A1_sv_1_NN_results610)%>%
  combine_LSTM_results_list(g3_A1_sv_1_LSTM_results_15, 0) %>%
  combine_FFORMA_results_list(g3_A1_sv_1_FFORMA_results) %>%
  combine_DeepAR_results_list(g3_A1_sv_1_DeepAR_results15, g3_A1_sv_1_DeepAR_results610)

# saveRDS(g1_A1_nosv_0_results_all, file =
#           "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_results_all.rds")
# saveRDS(g2_A1_nosv_0_results_all, file =
#           "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_results_all.rds")
# saveRDS(g3_A1_nosv_0_results_all, file =
#           "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_results_all.rds")

saveRDS(g1_A1_sv_0.01_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_results_all.rds")
saveRDS(g2_A1_sv_0.01_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_results_all.rds")
saveRDS(g3_A1_sv_0.01_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_results_all.rds")

saveRDS(g1_A1_sv_0.1_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_results_all.rds")
saveRDS(g2_A1_sv_0.1_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_results_all.rds")
saveRDS(g3_A1_sv_0.1_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_results_all.rds")

saveRDS(g1_A1_sv_1_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_results_all.rds")
saveRDS(g2_A1_sv_1_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_results_all.rds")
saveRDS(g3_A1_sv_1_results_all, file =
          "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_results_all.rds")
```

```{r load_final_results}
## Chunk to load final results list (just load this to avoid bothering with combining different results list)

g1_A1_nosv_0_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_nosv_0_results_all.RDS")
g2_A1_nosv_0_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_nosv_0_results_all.RDS")
g3_A1_nosv_0_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_nosv_0_results_all.RDS")

g1_A1_sv_0.01_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.01_results_all.RDS")
g2_A1_sv_0.01_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.01_results_all.RDS")
g3_A1_sv_0.01_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.01_results_all.RDS")

g1_A1_sv_0.1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_0.1_results_all.RDS")
g2_A1_sv_0.1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_0.1_results_all.RDS")
g3_A1_sv_0.1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_0.1_results_all.RDS")

g1_A1_sv_1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g1_A1_sv_1_results_all.RDS")
g2_A1_sv_1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g2_A1_sv_1_results_all.RDS")
g3_A1_sv_1_results_all <- readRDS("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/R/Model_results/g3_A1_sv_1_results_all.RDS")
```

```{r performance_functions}
## For a given simulation results list, collect all the loss dataframes into a big, tidy DF for a SINGLE realization

gen_tidy_loss_df <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  df <- foreach(sample = (1:3), .combine = "rbind") %do% {
    rbind(
      cbind(model = "LM_MSE", sample = sample, simulation_results_list[[realization_no]]$LM_MSE[[sample]]$loss_stats),
      cbind(model = "LM_MAE", sample = sample, simulation_results_list[[realization_no]]$LM_MAE[[sample]]$loss_stats),
      ################################################################################################
      cbind(model = "ELN_MSE", sample = sample, simulation_results_list[[realization_no]]$ELN_MSE[[sample]]$loss_stats),
      cbind(model = "ELN_MAE", sample = sample, simulation_results_list[[realization_no]]$ELN_MAE[[sample]]$loss_stats),
      ################################################################################################
      cbind(model = "RF_MSE", sample = sample, simulation_results_list[[realization_no]]$RF_MSE[[sample]]$loss_stats),
      cbind(model = "RF_MAE", sample = sample, simulation_results_list[[realization_no]]$RF_MAE[[sample]]$loss_stats),
      ################################################################################################
      cbind(model = "NN1_MSE", sample = sample, simulation_results_list[[realization_no]]$NN1_MSE[[sample]]$loss_stats),
      cbind(model = "NN1_MAE", sample = sample, simulation_results_list[[realization_no]]$NN1_MAE[[sample]]$loss_stats),

      cbind(model = "NN2_MSE", sample = sample, simulation_results_list[[realization_no]]$NN2_MSE[[sample]]$loss_stats),
      cbind(model = "NN2_MAE", sample = sample, simulation_results_list[[realization_no]]$NN2_MAE[[sample]]$loss_stats),

      cbind(model = "NN3_MSE", sample = sample, simulation_results_list[[realization_no]]$NN3_MSE[[sample]]$loss_stats),
      cbind(model = "NN3_MAE", sample = sample, simulation_results_list[[realization_no]]$NN3_MAE[[sample]]$loss_stats),

      cbind(model = "NN4_MSE", sample = sample, simulation_results_list[[realization_no]]$NN4_MSE[[sample]]$loss_stats),
      cbind(model = "NN4_MAE", sample = sample, simulation_results_list[[realization_no]]$NN4_MAE[[sample]]$loss_stats),

      cbind(model = "NN5_MSE", sample = sample, simulation_results_list[[realization_no]]$NN5_MSE[[sample]]$loss_stats),
      cbind(model = "NN5_MAE", sample = sample, simulation_results_list[[realization_no]]$NN5_MAE[[sample]]$loss_stats),
      #################################################################################################
      cbind(model = "LSTM_MSE", sample = sample, simulation_results_list[[realization_no]]$LSTM_MSE[[sample]]$loss_stats),
      cbind(model = "LSTM_MAE", sample = sample, simulation_results_list[[realization_no]]$LSTM_MAE[[sample]]$loss_stats),
      #################################################################################################
      cbind(model = "FFORMA_MSE", sample = sample, simulation_results_list[[realization_no]]$FFORMA_MSE[[sample]]$loss_stats),
      cbind(model = "FFORMA_MAE", sample = sample, simulation_results_list[[realization_no]]$FFORMA_MAE[[sample]]$loss_stats),
      #################################################################################################
      cbind(model = "DeepAR", sample = sample, simulation_results_list[[realization_no]]$DeepAR[[sample]]$loss_stats)
    )
  }
  cbind(realization_no = realization_no, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, df)
}

# Function to iterate over all realizations

all_realize_loss_df <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = (1:5), .combine = "rbind") %do% {
    gen_tidy_loss_df(simulation_results_list, realization_no, dgp_spec, SV, cross_corr)
  }
}

all_loss_df <- rbind(
  # all_realize_loss_df(g1_A1_nosv_0_results_all, dgp_spec = "g1", SV = 0, cross_corr = 0),
  # all_realize_loss_df(g2_A1_nosv_0_results_all, dgp_spec = "g2", SV = 0, cross_corr = 0),
  # all_realize_loss_df(g3_A1_nosv_0_results_all, dgp_spec = "g3", SV = 0, cross_corr = 0),
  
  all_realize_loss_df(g1_A1_sv_0.01_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.01),
  all_realize_loss_df(g2_A1_sv_0.01_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.01),
  all_realize_loss_df(g3_A1_sv_0.01_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.01),
  
  all_realize_loss_df(g1_A1_sv_0.1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.1),
  all_realize_loss_df(g2_A1_sv_0.1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.1),
  all_realize_loss_df(g3_A1_sv_0.1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.1),
  
  all_realize_loss_df(g1_A1_sv_1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 1),
  all_realize_loss_df(g2_A1_sv_1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 1),
  all_realize_loss_df(g3_A1_sv_1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 1)
)

all_loss_df_averaged <- all_loss_df %>%
  data.frame() %>%
  group_by(model, dgp_spec, sample, SV, cross_corr) %>%
  summarise(validation_MAE = mean(validation_MAE), validation_MSE = mean(validation_MSE), 
            validation_RMSE = mean(validation_RMSE), validation_RSquare = mean(validation_RSquare),
              
            test_MAE = mean(test_MAE), test_MSE = mean(test_MSE), 
            test_RMSE = mean(test_RMSE), test_RSquare = mean(test_RSquare)
            )

## Save to csv

write.csv(all_loss_df_averaged, file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_loss_averaged.csv")
write.csv(all_loss_df, file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_loss.csv")

########
## Take the above and average over all training/test samples to make cleaner graphs/tables

all_loss_df_averaged_sam <- all_loss_df_averaged %>%
  group_by(model, dgp_spec, SV, cross_corr) %>%
  summarise(validation_MAE = mean(validation_MAE), validation_MSE = mean(validation_MSE), 
            validation_RMSE = mean(validation_RMSE), validation_RSquare = mean(validation_RSquare),
              
            test_MAE = mean(test_MAE), test_MSE = mean(test_MSE), 
            test_RMSE = mean(test_RMSE), test_RSquare = mean(test_RSquare)
            )

write.csv(all_loss_df_averaged_sam, file = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_loss_averaged_sam.csv")

#############################################################################
# Function to collate variable importance

normalize_variable_importance <- function(variable_importance_df) {
  variable_importance_df %>%
    # Add a very very tiny value so that division by zero does not occur
    mutate(importance = importance + 1e-100) %>%
    mutate(importance = importance + abs(min(importance))) %>%
    mutate(importance = importance/sum(importance))
}

gen_tidy_vi <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  df <- foreach(sample = 1:3, .combine = "rbind") %do% {
    rbind(
      cbind(model = "LM_MSE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$LM_MSE[[sample]]$variable_importance)),
      cbind(model = "LM_MAE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$LM_MAE[[sample]]$variable_importance)),
      
      ################################################################################################
      
      cbind(model = "ELN_MSE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$ELN_MSE[[sample]]$variable_importance)),
      cbind(model = "ELN_MAE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$ELN_MAE[[sample]]$variable_importance)),
      
      ################################################################################################
      
      cbind(model = "RF_MSE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$RF_MSE[[sample]]$variable_importance)),
      cbind(model = "RF_MAE", sample = sample, 
            normalize_variable_importance(simulation_results_list[[realization_no]]$RF_MAE[[sample]]$variable_importance)),
      
      ################################################################################################
      
      cbind(model = "NN1_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN1_MSE[[sample]]$variable_importance)),
      cbind(model = "NN1_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN1_MAE[[sample]]$variable_importance)),

      cbind(model = "NN2_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN2_MSE[[sample]]$variable_importance)),
      cbind(model = "NN2_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN2_MAE[[sample]]$variable_importance)),

      cbind(model = "NN3_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN3_MSE[[sample]]$variable_importance)),
      cbind(model = "NN3_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN3_MAE[[sample]]$variable_importance)),

      cbind(model = "NN4_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN4_MSE[[sample]]$variable_importance)),
      cbind(model = "NN4_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN4_MAE[[sample]]$variable_importance)),

      cbind(model = "NN5_MSE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN5_MSE[[sample]]$variable_importance)),
      cbind(model = "NN5_MAE", sample = sample,
            normalize_variable_importance(simulation_results_list[[realization_no]]$NN5_MAE[[sample]]$variable_importance))
    )
  }
  cbind(realization_no = realization_no, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, df)
}

# Iterate over all realizations

all_realize_vi <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = (1:10), .combine = "rbind") %do% {
    gen_tidy_vi(simulation_results_list, realization_no, dgp_spec, SV, cross_corr)
  }
}

all_vi_df <- rbind(
  # all_realize_vi(g1_A1_nosv_0_results_all, dgp_spec = "g1", SV = 0, cross_corr = 0),
  # all_realize_vi(g2_A1_nosv_0_results_all, dgp_spec = "g2", SV = 0, cross_corr = 0),
  # all_realize_vi(g3_A1_nosv_0_results_all, dgp_spec = "g3", SV = 0, cross_corr = 0),
  
  all_realize_vi(g1_A1_sv_0.01_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.01),
  all_realize_vi(g2_A1_sv_0.01_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.01),
  all_realize_vi(g3_A1_sv_0.01_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.01),
  
  all_realize_vi(g1_A1_sv_0.1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 0.1),
  all_realize_vi(g2_A1_sv_0.1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 0.1),
  all_realize_vi(g3_A1_sv_0.1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 0.1),
  
  all_realize_vi(g1_A1_sv_1_results_all, dgp_spec = "g1", SV = 1, cross_corr = 1),
  all_realize_vi(g2_A1_sv_1_results_all, dgp_spec = "g2", SV = 1, cross_corr = 1),
  all_realize_vi(g3_A1_sv_1_results_all, dgp_spec = "g3", SV = 1, cross_corr = 1)
)

all_vi_df_averaged <- all_vi_df %>%
  group_by(model, dgp_spec, sample, SV, cross_corr, variable) %>%
  summarise(importance = mean(importance))
```

```{r prediction_performance_plots}
## Prediction Performance Plots

a4_aspect_ratio <- 1.5

#######################################################################
# Test Statistics

breaks <- levels(all_loss_df_averaged$model)
labels <- as.expression(breaks)
labels[[2]] <- bquote(bold(.(labels[[2]])))
labels[[4]] <- bquote(bold(.(labels[[4]])))
labels[[6]] <- bquote(bold(.(labels[[6]])))
labels[[16]] <- bquote(bold(.(labels[[16]])))

all_loss_df_averaged_sam %>%
  ungroup() %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_MAE), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_mae.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

all_loss_df_averaged_sam %>%
  ungroup() %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RMSE), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rmse.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

all_loss_df_averaged_sam %>%
  ungroup() %>%
  ggplot() +
  geom_bar(aes(x = model, y = test_RSquare), stat = "identity", position = position_dodge()) +
  scale_x_discrete(label = labels, breaks = breaks) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave(filename = "~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_test_rsquare.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

#################################
## TABLES
#################################

model_sam <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(model)

cross_corr_sam <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(cross_corr)

g1_sam_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MAE) %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g2_sam_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MAE) %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g3_sam_mae <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MAE) %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(-dgp_spec, -cross_corr)

#######

g1_sam_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MSE) %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g1") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g2_sam_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MSE) %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g2") %>%
  dplyr::select(-dgp_spec, -cross_corr)

g3_sam_mse <- all_loss_df_averaged_sam %>%
  ungroup() %>%
  dplyr::select(dgp_spec, cross_corr, test_MSE) %>%
  filter(cross_corr == 0.01 | cross_corr == 1) %>%
  filter(dgp_spec == "g3") %>%
  dplyr::select(-dgp_spec, -cross_corr)

cbind(model_sam, cross_corr_sam, g1_sam_mae, g2_sam_mae, g3_sam_mae) %>%
  kable(align = "c") %>%
  kable_styling(full_width = F) %>%
  add_header_above(c(" " = 1, " " = 1, "g1" = 1, "g2" = 1, "g3" = 1)) %>%
  collapse_rows(columns = c(1:2), valign = "top")

cbind(model_sam, cross_corr_sam, g1_sam_mse, g2_sam_mse, g3_sam_mse) %>%
  kable(align = "c") %>%
  kable_styling(full_width = F) %>%
  add_header_above(c(" " = 1, " " = 1, "g1" = 1, "g2" = 1, "g3" = 1)) %>%
  collapse_rows(columns = c(1:2), valign = "top")

```

```{r variable_importance_plots}
# Variable Importance Plots

breaks <- levels(all_vi_df_averaged$variable)
labels <- as.expression(breaks)
labels[[1]] <- bquote(bold(.(labels[[1]])))
labels[[2]] <- bquote(bold(.(labels[[2]])))
labels[[3]] <- bquote(bold(.(labels[[3]])))
labels[[303]] <- bquote(bold(.(labels[[303]])))

ggplot(data = data) + 
  geom_bar(aes(x = labs, y = counts), stat="identity") + 
  scale_x_discrete(label = labels, breaks = breaks)

## Plots for PRESENTATION

all_vi_df_averaged %>%
  filter(dgp_spec == "g1") %>%
  filter(model == "LM_MSE" 
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  group_by(dgp_spec, model, variable, cross_corr, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  top_n(10, importance) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, alpha = importance)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  # Facet
  facet_grid(rows = vars(cross_corr))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_g1_vi_plot.pdf")

all_vi_df_averaged %>%
  filter(dgp_spec == "g2") %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  group_by(dgp_spec, model, sample, cross_corr, SV) %>%
  top_n(2, importance) %>%
  ggplot() + 
  geom_tile(aes(x = model, y = variable, alpha = importance)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(sample))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_g2_vi_plot.pdf")

all_vi_df_averaged %>%
  filter(dgp_spec == "g3") %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  group_by(dgp_spec, model, sample, cross_corr, SV) %>%
  top_n(2, importance) %>%
  ggplot() + 
  geom_tile(aes(x = model, y = variable, alpha = importance)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(sample))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_g3_vi_plot.pdf")

## Average variable importance over all samples

all_vi_df_averaged %>%
  filter(model == "LM_MSE" 
         | model == "ELN_MAE"
         | model == "RF_MAE"
         | model == "NN5_MAE") %>%
  group_by(dgp_spec, model, cross_corr, variable, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  group_by(model) %>%
  top_n(42, importance) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, alpha = importance)) +
  scale_x_discrete(label = labels, breaks = breaks) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_ave_vi_plot_pre.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

all_vi_df_averaged %>%
  filter(model == "NN1_MAE"
         | model == "NN2_MAE"
         | model == "NN3_MAE"
         | model == "NN4_MAE"
         | model == "NN5_MAE") %>%
  group_by(dgp_spec, model, cross_corr, variable, SV) %>%
  summarise(importance = mean(importance)) %>%
  ungroup() %>%
  mutate(variable = fct_reorder(variable, importance)) %>%
  group_by(model) %>%
  top_n(60, importance) %>%
  ggplot() + 
  geom_tile(aes(x = variable, y = model, alpha = importance)) +
  scale_x_discrete(label = labels, breaks = breaks) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position = "none") +
  # Facet
  facet_grid(rows = vars(cross_corr), cols = vars(dgp_spec))
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/simulation_ave_vi_plot_pre_nn.pdf",
       width = 15 * a4_aspect_ratio, height = 15, units = "cm")

```

```{r hyperparam_functions}
## Plotting hyperparameters of ELN across different training samples

# Function to extract ELN hyperparameter df from simulation results list

get_eln_hyper_df <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  foreach(sample = 1:3, .combine = "rbind") %do% {
    rbind(
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "ELN_MSE",
            simulation_results_list[[realization_no]]$ELN_MSE[[sample]]$hyperparameters),
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "ELN_MAE",
            simulation_results_list[[realization_no]]$ELN_MAE[[sample]]$hyperparameters)
      )
  }
}

# Iterate this over all realizations

iterate_over_realization <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = 1:10, .combine = "rbind") %do% {
    get_eln_hyper_df(simulation_results_list, realization_no = realization_no, dgp_spec, SV, cross_corr)
  }
}

eln_hyperparameters_df <- rbind(
  iterate_over_realization(g1_A1_nosv_0_results, "g1", 0, 0),
  iterate_over_realization(g2_A1_nosv_0_results, "g2", 0, 0),
  iterate_over_realization(g3_A1_nosv_0_results, "g3", 0, 0),
  
  iterate_over_realization(g1_A1_sv_0.01_results, "g1", 1, 0.01),
  iterate_over_realization(g2_A1_sv_0.01_results, "g2", 1, 0.01),
  iterate_over_realization(g3_A1_sv_0.01_results, "g3", 1, 0.01),
  
  iterate_over_realization(g1_A1_sv_0.1_results, "g1", 1, 0.1),
  iterate_over_realization(g2_A1_sv_0.1_results, "g2", 1, 0.1),
  iterate_over_realization(g3_A1_sv_0.1_results, "g3", 1, 0.1),
  
  iterate_over_realization(g1_A1_sv_1_results, "g1", 1, 1),
  iterate_over_realization(g2_A1_sv_1_results, "g2", 1, 1),
  iterate_over_realization(g3_A1_sv_1_results, "g3", 1, 1)
)

## Alpha value plot
eln_hyperparameters_df %>%
  mutate(group_id = group_indices(., realization_no, model, dgp_spec, SV, cross_corr)) %>%
  mutate(group_id = as.factor(group_id)) %>%
  ggplot() +
  geom_line(aes(x = sample, y = alpha, group = group_id, colour = group_id)) +
  theme_bw() +
  theme(legend.position = "none")
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/eln_alpha_plot.pdf")

## Lambda Value Plot
eln_hyperparameters_df %>%
  mutate(group_id = group_indices(., realization_no, model, dgp_spec, SV, cross_corr)) %>%
  mutate(group_id = as.factor(group_id)) %>%
  ggplot() +
  geom_line(aes(x = sample, y = lambda, group = group_id, colour = group_id)) +
  theme_bw() +
  theme(legend.position = "none")
ggsave("~/GitHub/Evaluation-of-Machine-Learning-in-Asset-Pricing/Results/eln_lambda_plot.pdf")
```

```{r hyperparam_plots}
## Plotting hyperparameters of randomforest across training samples

get_rf_hyper_df <- function(simulation_results_list, realization_no, dgp_spec, SV, cross_corr) {
  foreach(sample = 1:3, .combine = "rbind") %do% {
    rbind(
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "RF_MSE",
            simulation_results_list[[realization_no]]$RF_MSE[[sample]]$hyperparameters),
      cbind(realization_no = realization_no, sample = sample, dgp_spec = dgp_spec, SV = SV, cross_corr = cross_corr, model = "RF_MAE",
            simulation_results_list[[realization_no]]$RF_MAE[[sample]]$hyperparameters)
      )
  }
}

iterate_over_realization <- function(simulation_results_list, dgp_spec, SV, cross_corr) {
  foreach(realization_no = 1:10, .combine = "rbind") %do% {
    get_rf_hyper_df(simulation_results_list, realization_no = realization_no, dgp_spec, SV, cross_corr)
  }
}

rf_hyperparameters_df <- rbind(
  iterate_over_realization(g1_A1_nosv_0_results, "g1", 0, 0),
  iterate_over_realization(g2_A1_nosv_0_results, "g2", 0, 0),
  iterate_over_realization(g3_A1_nosv_0_results, "g3", 0, 0),
  
  iterate_over_realization(g1_A1_sv_0.01_results, "g1", 1, 0.01),
  iterate_over_realization(g2_A1_sv_0.01_results, "g2", 1, 0.01),
  iterate_over_realization(g3_A1_sv_0.01_results, "g3", 1, 0.01),
  
  iterate_over_realization(g1_A1_sv_0.1_results, "g1", 1, 0.1),
  iterate_over_realization(g2_A1_sv_0.1_results, "g2", 1, 0.1),
  iterate_over_realization(g3_A1_sv_0.1_results, "g3", 1, 0.1),
  
  iterate_over_realization(g1_A1_sv_1_results, "g1", 1, 1),
  iterate_over_realization(g2_A1_sv_1_results, "g2", 1, 1),
  iterate_over_realization(g3_A1_sv_1_results, "g3", 1, 1)
)

rf_hyperparameters_df %>%
  mutate(group_id = group_indices(., realization_no, model, dgp_spec, SV, cross_corr)) %>%
  mutate(group_id = as.factor(group_id)) %>%
  ggplot() +
  geom_line(aes(x = sample, y = mtry, group = group_id, colour = group_id)) +
  theme_bw() +
  theme(legend.position = "none")
```
