---
title: "aws_prep"
author: "Ze Yu Zhong"
date: "19 June 2019"
output: html_document
---

```{r setup, include=FALSE}
################
##Load Libraries
################

library(speedglm)
library(tidyverse)
library(keras)
library(ggplot2)
library(forecast)
library(rlist)
library(Metrics)
library(tensorflow)
library(quantreg)
library(randomForestSRC)
library(hqreg)
library(caret)
library(tsfeatures)
library(jsonlite)

## Vector arima/garch packages

library(kernlab)
library(xts)
library(tsne)
library(rmgarch)
library(marima)
library(jsonlite)

#Parallel Computing
library(foreach)
library(doFuture)
#Registering
registerDoFuture()
plan(multisession)
```

```{r}
pooled_panel <- readRDS("pooled_panel.rds")
```

```{r}
## Testing out streaming in json files, from exmaple sagemaker output
## This is confirmed to be working, just need to figure out how to get pooled_panel into the right format
## Note that fromJSON does not work, unless you add in [ and ] to the start and end of the JSOn file respectively
json_test <- stream_in(file("train_new_features.json"))

toJSON(json_test)
```

```{r}
## 
tidy_to_json <- function(data) {
  stock_id <- data$stock %>%
    unique()
  
  # Number of cross sectional units
  cross_units <- length(stock_id)
  
  ## JUst setting the beginning time to something arbitrary for now, change if needed
  pooled_panel_json <- data.frame(start = rep("2000-01-01 00:00:00", cross_units), 
                                  target = c(1:cross_units), 
                                  dynamic_feat = c(1:cross_units))
  
  for (i in 1:cross_units) {
    pooled_panel_filter <- data %>%
      filter(stock == stock_id[i])
    
    pooled_panel_json$target[i] <- list(pooled_panel_filter$rt)
    
    pooled_panel_filter_feature <- pooled_panel_filter %>%
      select(-time, -rt, -stock) %>%
      unname() %>%
      as.matrix() %>%
      # Transpose it to get the right format of one feature series per row
      t()
    
    pooled_panel_json[i, ]$dynamic_feat <- pooled_panel_filter_feature %>% list()
  }
  
  pooled_panel_json
}
```


```{r}
## JSON manipulation for use with AWS inference format

## Unlike the actual training/validation data, inference format is annoyingly different (again)

## Below is some dummy data, and shows us the format we need for it to work with AWS inference

test <- fromJSON("inference_test.json")
json %>% 
  data.frame() %>%
  stream_out()

# Ie we want a list of 2:
# instances
  # start = vector of string of start dates
  # target = list length = number of time series, each containing a vector of that time series
  # dynamic feat = list = number of time series, each containing a data frame of the dynamic features (same format as training)
# configuration
  # num_samples
  # output_types
  # quantiles


pooled_panel_json <- pooled_panel %>% tidy_to_json()

list(start = pooled_panel_json$start, 
     target = pooled_panel_json$target, 
     dynamic_feat = pooled_panel_json$dynamic_feat)

## Configuration List
list(num_samples = 10, output_types = c("mean", "quantiles", "samples"), quantiles = c("0.5"))
```
