---
title: "Simulation"
author: "Ze Yu Zhong, Edits by David Frazier"
date: "27-05-2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
################
##Load Libraries
################

library(glmnet)
library(tidyverse)
library(keras)
library(ggplot2)
library(caret)
library(forecast)
library(rlist)
library(plm)
library(Metrics)
library(ranger)

set.seed(27935248)
```

```{r global_options}
#####################################
##Simulation
#####################################
rm(list=ls())
#Number of stocks
# N <- 200
# #Number of characteristics that underly true model
# P_c <- 100
# #Number of Periods
# Time <- 180

N <- 200

P_c <- 100

Time <- 180

```



```{r function_simulate_characteristics}
###################
##characteristics C_bar
###################

#######
##Function to Generate C_bar
#######

gen_C_bar <- function(){
  #empty matrix
  elm <- matrix(
    data = 0, nrow = N, ncol = P_c
  )
  
  C_bar <- rep(list(elm), Time + 2)
  
  #Generate rho vector to be constant across time and stocks
 # rho <- runif(P_c, .9, 1)
  rho<- c(.5,.5,.5)
  # Lower values here give higher time series correlation, and lower cr
  for (t in 1:(Time+1)) {
    for (j in 1:P_c) {
      C_bar[[t+1]][, j] <- (C_bar[[t]][, j] * rho[j] + rnorm(N, 0, 1))
    }  
  }
  
  ##Delete first period full of zeroes
  C_bar[[1]] <- NULL
  
  return(C_bar)
}

#######################################
##Generate correlation matrix
#######################################

gen_W <- function(){
  
  #Generate Lambda Matrix first
  
  Lambda <- matrix(
    data = rnorm(N*4, 0, 1),
    nrow = N, ncol = 4
  )
  
  #Use Lambda to create B matrix
  
  B <- (Lambda) %*% t(Lambda)
  B <- B + 1/10*diag(nrow = nrow(B))
  
  #Turn B into a correlation matrix
  
  W <- diag(B)^(-1/2)*B*diag(B)^(-1/2)
  return(W)
}

#########################
##Generate C_hat
#########################
#This builds in the correlation from W into original C_bar

gen_C_hat <- function(){
  W <- gen_W()
  
  C_hat <- rep(list(elm), Time + 1)

  for (t in 1:(Time+1)) {
    C_hat[[t]] <- W %*% C_bar[[t]]
  }
  
  return(C_hat)
}

##################################
##Generate final "observed" C
##################################

#This function "observes" characteristics by normalizing them within (-1, 1) via the rank transformation

# DAVID: I was getting weird things here when I tried the code. So I used a 3-d array instead of a list. Easier for me to think in terms of matrices

gen_C <- function(C_matrix){
 # C <- rep(list(elm), Time+1)
  temp <- matrix(0,N,P_c)
  
  C<- array(temp,c(N,P_c,(Time+1)))
  for (t in 1:(Time+1)) {
    C[,,t] <- (2/(N*P_c+1))*
      matrix(rank(C_matrix[[t]]), nrow = N, ncol = P_c) - matrix(
        data = 1, nrow = N, ncol = P_c
        )
  }
  
  return(C)
}
```

```{r generate_characteristics}
C_bar <- gen_C_bar()
#C_hat <- gen_C_hat()
#C <- gen_C()
 C<- gen_C(C_bar)
```


```{r function_generate_xt}
########################
##xt set up
########################

########################
##Specify A Matrices
########################

A1 <- matrix(c(
  0.95, 0, 0,
  0, 0.95, 0,
  0, 0, 0.95),
  nrow = 3, ncol = 3
)

A2 <- matrix(c(
  1, 0, 0.25,
  0, 0.95, 0,
  0.25, 0, 0.95),
  nrow = 3, ncol = 3
)

A3 <- matrix(c(
  0.99, 0.2, 0.1,
  0.2, 0.90, -0.3,
  0.1, -0.3, -0.99),
  nrow = 3, ncol = 3
)

###################################
###Function to Generate xt series
###################################
#xt is a multivariate time series with 3 different series
#Generates xt series, given A matrix specification

gen_xt <- function(A){
  
  xt <- data.frame(x1 = c(0:Time),
                   x2 = c(0:Time),
                   x3 = c(0:Time)
  )
  
  Axt <- xt
  for (i in 1:(Time+1)) {
    ut <- rnorm(3, mean = 0, sd = 1)*(1-.95^2)
    Axt[1+i,] <- Axt[i,] + ut
  }
  Axt <- Axt[-1,]
  return(Axt)
}

#########################################
##Function to plot xt
#########################################

#Transforms xt series to wide format and plots it

plot_xt <- function(xt){
  xt_tidy <- cbind(t = c(1:(Time+1)), xt)

  xt_tidy <- xt_tidy %>%
    gather(series, value, -t)
  
  ggplot(data = xt_tidy) +
    geom_line(aes(x = t, y = value, colour = series))
}

```


```{r function_g}
############################
##Different g() functions
############################

#Logit function, used in some specified structures

logit <- function(x){
  (1 + exp(-x))^(-1)
}

#Remmeber that theta needs to be tuned later. Set up all of the functions as functions of theta

##############################
#g1
##############################

#Default theta, 1x3 dimensions
theta <- matrix(c(0.02, 0.02, 0.02), nrow = 1)

#g1 <- function(C, x, i, t, theta){
#  
#  matrix(c(
#    C[[t]][i,1], C[[t]][i,2], C[[t]][i,3] * t(x[t, 3])
#    ), nrow = 1) %*% t(theta)
#}

# David: Need to change these functions if you are going to go with the array approach. 
#g1 <- function(C, x, i, t, theta){
#  matrix(c(
#    C[[t]][i,1], C[[t]][i,2], C[[t]][i,3] * t(x[t, 3])
#    ), nrow = 1) %*% t(theta)
#}

g1<- function(C,x,theta)
{
  Reg_fun<- matrix(0,N,(Time+1))
  for (i in 1:N)
  {  
#  Reg_fun[i,]<-cbind(C[,1:2,t],as.vector(C[,3,t]*as.numeric(x[t,1])))%*%t(theta)
  Reg_fun[i,]<-cbind(t(C[i,1:2,]),(as.matrix(C[i,3,]*as.matrix(x[,1]))))%*%t(theta)
  
}
#Reg_fun
return (Reg_fun)
}
  
  
#test if working
#t<-g1(C_bar, xt, 1, 1, theta)

##############################
#g2
##############################

#Default theta, 1x3 dimensions
theta <- matrix(c(0.04, 0.035, 0.01), nrow = 1)

g2 <- function(C, x, i, t, theta){
  matrix(c(
    C[[t]][i, 1]^2, 
    C[[t]][i, 1]*C[[t]][i, 2],
    sign(
      C[[t]][i, 3] * t(x[t, 3])
      )
  ), nrow = 1) %*% t(theta)
}

#test if working
#g2(C, xt, 1, 1, theta)

#############################
#g3
#############################

#Default theta, 1x4 dimensions
theta <- matrix(c(0.04, 0.035, 0.01, 0.01), nrow = 1)

g3 <- function(C, x, i, t, theta){
  matrix(
    c(
      (C[[t]][i, 1] > 0), 
      C[[t]][i, 2]^3,
      C[[t]][i, 1] * C[[t]][i, 2] * (C[[t]][i, 3] > 0),
      logit(C[[t]][i, 3])
      ),
    nrow = 1) %*% t(theta)
}

#test if working
#g3(C, xt, 1, 1, theta)


#################################
#g4
#Remember that we are supposed to pass C hat through to g4
#################################

#Default theta, 1x3 dimensions
theta <- matrix(c(0.02, 0.02, 0.02), nrow = 1)

g4 <- function(C, x, i, t, theta){
  matrix(c(
    C[[t]][i, 1],
    C[[t]][i, 2],
    C[[t]][i, 3]*t(x[t, 3])
    ), nrow = 1
  ) %*% t(theta)
}

#test if working
#g4(C_hat, xt, 1, 1, theta)

#################################

```

```{r function_return_equation}
##########################
##Functions for elements in return equation
##########################

###########
##Function to generate Beta, i,t
###########

gen_Beta <- function(){
  Beta<- C[,1:3,]
}

gen_v <- function(v_sd){
 # This is way too complicated. The same thing can be achieved with a single line of code.
  
  v<-matrix( rnorm(3*(Time+1),mean=0,sd=1), (Time+1),3)*.05^2 
  return(v)
}
  
#############################
##Error Structure
#############################

##Specify omega, gamma and w
omega <- -0.736
gamma <- 0.90
w <- sqrt(0.363)
##

#############################
##Function to generate errors
#############################

gen_error <- function(omega, gamma, w){
  
  ##Generate Sigma first
  
  sigma2 <- rep(list(0), Time+1)
  
  sigma2[[1]] <- omega + w
  
  for (t in 1:Time+1) {
    sigma2[[t+1]] <- omega + gamma*sigma2[[t]] + rnorm(1, 0, w)
  }
  
  sigma2[[1]] <- NULL
  
  ##Generate Errors
  #Turning off the SV componennts for now. 
  #
  error <- matrix( rnorm(N*(Time+1),mean=0,sd=1), N, (Time+1))*.05^2 
  return(error)
}

```

```{r function_generate_return}
############################################################################
##Function to generate return series + its residuals given specification of A and g function
############################################################################

#This generates beta, v vector of errors, and the epsilon errors, then binds them together for the final error term

gen_rt_resid <- function(omega, gamma, w, v_sd){
#  elp <- matrix(0, nrow = N, ncol = 1)
  
#  resid <- rep(list(elp), Time+1)
  
  ##############################
  Beta <- gen_Beta()
  v <- gen_v(v_sd)
  error <- matrix( rnorm(N*(Time+1),mean=0,sd=1), N, (Time+1))*.05 
  ##############################
  resid<-matrix(0,N,(Time+1))
  for (i in 1:N){
  resid[i,] <- rowSums(t(as.matrix(Beta[i,,]))*v) + error[i,]
  }
#  for (t in 1:(Time)) {
 #   for (i in 1:N){
#      resid[[t]][i] <- Beta[[t]][i, ] %*% v[[t]] + error[[t]][i]
#    }
#  }
  
  return(resid)
}


#for (i in 1:20){ 
#Xs<- t(as.matrix(Beta[i,,]))*v  
#Y<- resid[i,]  
#df<- data.frame(Y,Xs)
#  fit<- lm(Y~Xs,df)    
#summary(fit)$r.squared  
#  }

#This generates the final return series, given the residuals (to be generated using above function)
  #########################
# Axt <- gen_xt(A1)
  #########################

#########################
# Generate a single X series for now
#########################


x<- matrix(0,(Time+1),1)
ers<- rnorm((Time+1),0,1)*(1-.95^2)
x[1,1]<-ers[1]
for (t in 2:(Time+1))
{
  
x[t,]<- .95 *x[t-1,]+ers[t]  
  
  
}


res<- gen_rt_resid(omega, gamma, w, v_sd)
Reg_fun<-g1(C,x,theta)
rt<- Reg_fun+res



```




```{r tune_rsquared_skeleton}
#Tuning Cross Sectional R Squared SKELETON CODE

#We want individual r squared for each stock to be 50%
#We want individual annualized volatility to be 30%
#We want to cross sectional R squared to be 25%
#We want the predictive R squared to be 5%

#Generate paramaters first

#Tune v_sd for inidividual r square first
#Gu et al had 0.05 for their v variance
v_sd <- 0.05

#Tune SV parameters for individual r square first
#Not too sure about stochastic volatility parameters

  # #Defaults
  # omega <- -0.736
  # gamma <- 0.90
  # w <- sqrt(0.363)

#theta <- matrix(c(0.02, 0.02, 0.02), nrow = 1)
#rt<- g1(C,x,theta)+resid

##########################################
# Time series R-squared
##########################################
  Rsquared<-matrix(0,N,1)
  SSR<-matrix(0,N,1)
  SST<-matrix(0,N,1)
  Fits<-matrix(0,(Time+1),N)
  Coeff_Betas<-matrix(0,N,3)
  Xs_bar<-matrix(0,N,3)
  R_bar<-matrix(0,N,1)
  Resids<-matrix(0,(Time+1),N)
  for (i in 1:N)
{
  Rs<- rt[i,]
  R_bar[i,1]<-mean(Rs)
  Xs<- cbind(t(C[i,1:2,]),(as.matrix(C[i,3,]*as.matrix(x[,1]))))
  Xs_bar[i,]<- colMeans(Xs)
  df<-data.frame(Rs,Xs)
  fit<-lm(Rs ~., df)
  Fits[,i]<- fit$fitted.values
  Coeff_Betas[i,]<-as.numeric(fit$coefficients[2:4])
  Resids[,i]<- fit$residuals
  SSR[i,1]<- sum(Resids[,i]^2)
  SST[i,1]<- sum((Rs-mean(Rs))^2)
  
  
  Rsquared[i,1]<-summary(fit)$r.squared
  
  }
mean(Rsquared)

val<-g1(C,x,theta)
true_res<- rowSums( (rt - val)^2)
true_sst<- rowSums((rt-rowMeans(rt))^2)
true_rRsquared <- 1-(sum(true_res)/sum(true_sst))

fitted_Rsquared<- 1-(sum(SSR)/sum(SST))

##########################################
# Cross-sectional R-squared
##########################################

R_bar <- rowMeans(rt)
df_new <- data.frame(R_bar,Coeff_Betas) 

cross_fit <- lm(R_bar~ Coeff_Betas, df_new) 
summary(cross_fit)

```




